//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class ActorRenderWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(ActorRender), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("SetRenderList", SetRenderList);
		L.RegFunction("SetIsLowMaterial", SetIsLowMaterial);
		L.RegFunction("SetRenderMaterial", SetRenderMaterial);
		L.RegFunction("SetIsCastShadow", SetIsCastShadow);
		L.RegFunction("SetIsDisableAllAttachEffects", SetIsDisableAllAttachEffects);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetRenderList(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ActorRender obj = (ActorRender)ToLua.CheckObject<ActorRender>(L, 1);
			System.Collections.Generic.List<ActorRender.RenderItem> arg0 = (System.Collections.Generic.List<ActorRender.RenderItem>)ToLua.CheckObject(L, 2, typeof(System.Collections.Generic.List<ActorRender.RenderItem>));
			obj.SetRenderList(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetIsLowMaterial(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 3);
			ActorRender obj = (ActorRender)ToLua.CheckObject<ActorRender>(L, 1);
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			bool arg1 = LuaDLL.luaL_checkboolean(L, 3);
			obj.SetIsLowMaterial(arg0, arg1);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetRenderMaterial(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ActorRender obj = (ActorRender)ToLua.CheckObject<ActorRender>(L, 1);
			UnityEngine.Material arg0 = (UnityEngine.Material)ToLua.CheckObject<UnityEngine.Material>(L, 2);
			obj.SetRenderMaterial(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetIsCastShadow(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ActorRender obj = (ActorRender)ToLua.CheckObject<ActorRender>(L, 1);
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.SetIsCastShadow(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetIsDisableAllAttachEffects(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			ActorRender obj = (ActorRender)ToLua.CheckObject<ActorRender>(L, 1);
			bool arg0 = LuaDLL.luaL_checkboolean(L, 2);
			obj.SetIsDisableAllAttachEffects(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

