//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class MaterialSwitcherWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(MaterialSwitcher), typeof(UnityEngine.MonoBehaviour));
		L.RegFunction("Switch", Switch);
		L.RegFunction("__eq", op_Equality);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Switch(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 2 && TypeChecker.CheckTypes<string>(L, 2))
			{
				MaterialSwitcher obj = (MaterialSwitcher)ToLua.CheckObject<MaterialSwitcher>(L, 1);
				string arg0 = ToLua.ToString(L, 2);
				obj.Switch(arg0);
				return 0;
			}
			else if (count == 2 && TypeChecker.CheckTypes<int>(L, 2))
			{
				MaterialSwitcher obj = (MaterialSwitcher)ToLua.CheckObject<MaterialSwitcher>(L, 1);
				int arg0 = (int)LuaDLL.lua_tonumber(L, 2);
				obj.Switch(arg0);
				return 0;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: MaterialSwitcher.Switch");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int op_Equality(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 2);
			UnityEngine.Object arg0 = (UnityEngine.Object)ToLua.ToObject(L, 1);
			UnityEngine.Object arg1 = (UnityEngine.Object)ToLua.ToObject(L, 2);
			bool o = arg0 == arg1;
			LuaDLL.lua_pushboolean(L, o);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

