//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class Nirvana_WebViewWrap
{
	public static void Register(LuaState L)
	{
		L.BeginStaticLibs("WebView");
		L.RegFunction("Open", Open);
		L.EndStaticLibs();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Open(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			string arg0 = ToLua.CheckString(L, 1);
			Nirvana.WebView.Open(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

