//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class QingGongStateWrap
{
	public static void Register(LuaState L)
	{
		L.BeginEnum(typeof(QingGongState));
		L.RegVar("None", get_None, null);
		L.RegVar("Up", get_Up, null);
		L.RegVar("Down", get_Down, null);
		L.RegVar("ReadyToGround", get_ReadyToGround, null);
		L.RegVar("OnGround", get_OnGround, null);
		L.RegFunction("IntToEnum", IntToEnum);
		L.EndEnum();
		TypeTraits<QingGongState>.Check = CheckType;
		StackTraits<QingGongState>.Push = Push;
	}

	static void Push(IntPtr L, QingGongState arg)
	{
		ToLua.Push(L, arg);
	}

	static bool CheckType(IntPtr L, int pos)
	{
		return TypeChecker.CheckEnumType(typeof(QingGongState), L, pos);
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_None(IntPtr L)
	{
		ToLua.Push(L, QingGongState.None);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Up(IntPtr L)
	{
		ToLua.Push(L, QingGongState.Up);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Down(IntPtr L)
	{
		ToLua.Push(L, QingGongState.Down);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_ReadyToGround(IntPtr L)
	{
		ToLua.Push(L, QingGongState.ReadyToGround);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_OnGround(IntPtr L)
	{
		ToLua.Push(L, QingGongState.OnGround);
		return 1;
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int IntToEnum(IntPtr L)
	{
		int arg0 = (int)LuaDLL.lua_tonumber(L, 1);
		QingGongState o = (QingGongState)arg0;
		ToLua.Push(L, o);
		return 1;
	}
}

