//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class SceneOptimizeMgrWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(SceneOptimizeMgr), typeof(System.Object));
		L.RegFunction("StaticBatch", StaticBatch);
		L.RegFunction("New", _CreateSceneOptimizeMgr);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateSceneOptimizeMgr(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				SceneOptimizeMgr obj = new SceneOptimizeMgr();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: SceneOptimizeMgr.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int StaticBatch(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			SceneOptimizeMgr.StaticBatch();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

