return {
	actorController = {
		projectiles = {
			{
				Action = "attack5",
				HurtPosition = 0,
				Projectile = {
					BundleName = "effects/prefab/role/1003/attack5_zidan_prefab",
					AssetName = "attack5_zidan",
				},
				ProjectilGoName = "attack5_zidan",
				FromPosHierarchyPath = "buff_down",
				DelayProjectileEff = 0.1,
				DeleProjectileDelay = 0.0,
				ProjectilNodeHierarchyPath = "",
				ProjectileBtnName = "atk5",
			},
			{
				Action = "attack11",
				HurtPosition = 0,
				Projectile = {
					BundleName = "effects/prefab/other/xiannv_qunshang_prefab",
					AssetName = "xiannv_qunshang",
				},
				ProjectilGoName = "xiannv_qunshang",
				FromPosHierarchyPath = "guadian_Head",
				DelayProjectileEff = 0.0,
				DeleProjectileDelay = 0.0,
				ProjectilNodeHierarchyPath = "",
				ProjectileBtnName = "attack11",
			},
		},
		hurts = {},

		beHurtEffecct = {},

		hurtEffectName = "",
		beHurtNodeName = "",
		beHurtAttach = false,
		hurtEffectFreeDelay = 0.0,
		QualityCtrlList = {},

	},
	actorTriggers = {
		effects = {
			{
				triggerEventName = "attack4/begin",
				triggerDelay = 0.0,
				triggerFreeDelay = 0.0,
				effectGoName = "1003_attack01_xc",
				effectAsset = {
					BundleName = "effects/prefab/role/1003/1003_attack01_xc_prefab",
					AssetName = "1003_attack01_xc",
				},
				playerAtTarget = false,
				referenceNodeHierarchyPath = "",
				isAttach = false,
				isRotation = false,
				triggerStopEvent = "",
				effectBtnName = "attack",
			},
			{
				triggerEventName = "attack2/begin",
				triggerDelay = 0.1,
				triggerFreeDelay = 0.0,
				effectGoName = "1003_attack2_xc",
				effectAsset = {
					BundleName = "effects/prefab/role/1003/1003_attack2_xc_prefab",
					AssetName = "1003_attack2_xc",
				},
				playerAtTarget = false,
				referenceNodeHierarchyPath = "",
				isAttach = false,
				isRotation = false,
				triggerStopEvent = "",
				effectBtnName = "attack2",
			},
			{
				triggerEventName = "attack1/begin",
				triggerDelay = 0.0,
				triggerFreeDelay = 0.0,
				effectGoName = "1003001_Attack3_dcq02",
				effectAsset = {
					BundleName = "effects/prefab/role/1003/1003001_attack3_dcq02_prefab",
					AssetName = "1003001_Attack3_dcq02",
				},
				playerAtTarget = false,
				referenceNodeHierarchyPath = "",
				isAttach = false,
				isRotation = true,
				triggerStopEvent = "",
				effectBtnName = "attack3_2",
			},
			{
				triggerEventName = "attack1/begin",
				triggerDelay = 0.6,
				triggerFreeDelay = 0.0,
				effectGoName = "1003001_Attack3_xc",
				effectAsset = {
					BundleName = "effects/prefab/role/1003/1003001_attack3_xc_prefab",
					AssetName = "1003001_Attack3_xc",
				},
				playerAtTarget = false,
				referenceNodeHierarchyPath = "",
				isAttach = false,
				isRotation = false,
				triggerStopEvent = "",
				effectBtnName = "attack3_3",
			},
			{
				triggerEventName = "attack3/begin",
				triggerDelay = 0.0,
				triggerFreeDelay = 0.0,
				effectGoName = "1003001_Attack4_xc",
				effectAsset = {
					BundleName = "effects/prefab/role/1003/1003001_attack4_xc_prefab",
					AssetName = "1003001_Attack4_xc",
				},
				playerAtTarget = false,
				referenceNodeHierarchyPath = "",
				isAttach = false,
				isRotation = true,
				triggerStopEvent = "",
				effectBtnName = "attack4",
			},
			{
				triggerEventName = "combo1_1/begin",
				triggerDelay = 0.0,
				triggerFreeDelay = 0.0,
				effectGoName = "1003001_Combo1_dcq01",
				effectAsset = {
					BundleName = "effects/prefab/role/1003/1003001_combo1_dcq01_prefab",
					AssetName = "1003001_Combo1_dcq01",
				},
				playerAtTarget = false,
				referenceNodeHierarchyPath = "",
				isAttach = false,
				isRotation = true,
				triggerStopEvent = "",
				effectBtnName = "combo1",
			},
			{
				triggerEventName = "combo1_2/begin",
				triggerDelay = 0.0,
				triggerFreeDelay = 0.0,
				effectGoName = "1003001_Combo2_dcq02",
				effectAsset = {
					BundleName = "effects/prefab/role/1003/1003001_combo2_dcq02_prefab",
					AssetName = "1003001_Combo2_dcq02",
				},
				playerAtTarget = false,
				referenceNodeHierarchyPath = "",
				isAttach = false,
				isRotation = true,
				triggerStopEvent = "",
				effectBtnName = "combo2",
			},
			{
				triggerEventName = "combo1_3/begin",
				triggerDelay = 0.0,
				triggerFreeDelay = 0.0,
				effectGoName = "1003001_Combo3_dcq03",
				effectAsset = {
					BundleName = "effects/prefab/role/1003/1003001_combo3_dcq03_prefab",
					AssetName = "1003001_Combo3_dcq03",
				},
				playerAtTarget = false,
				referenceNodeHierarchyPath = "",
				isAttach = false,
				isRotation = true,
				triggerStopEvent = "",
				effectBtnName = "combo3",
			},
			{
				triggerEventName = "attack6/begin",
				triggerDelay = 0.0,
				triggerFreeDelay = 0.0,
				effectGoName = "Buff_zhuahen",
				effectAsset = {
					BundleName = "effects/prefab/buff/buff_zhuahen_prefab",
					AssetName = "Buff_zhuahen",
				},
				playerAtTarget = false,
				referenceNodeHierarchyPath = "",
				isAttach = false,
				isRotation = false,
				triggerStopEvent = "",
				effectBtnName = "attack6",
			},
			{
				triggerEventName = "attack7/begin",
				triggerDelay = 0.0,
				triggerFreeDelay = 0.0,
				effectGoName = "BUFF_fuhuo",
				effectAsset = {
					BundleName = "effects/prefab/buff/buff_fuhuo_prefab",
					AssetName = "BUFF_fuhuo",
				},
				playerAtTarget = false,
				referenceNodeHierarchyPath = "",
				isAttach = false,
				isRotation = false,
				triggerStopEvent = "",
				effectBtnName = "attack7",
			},
			{
				triggerEventName = "attack8/begin",
				triggerDelay = 0.0,
				triggerFreeDelay = 0.0,
				effectGoName = "BUFF_wudi_01",
				effectAsset = {
					BundleName = "effects/prefab/buff/buff_wudi_01_prefab",
					AssetName = "BUFF_wudi_01",
				},
				playerAtTarget = false,
				referenceNodeHierarchyPath = "",
				isAttach = false,
				isRotation = false,
				triggerStopEvent = "",
				effectBtnName = "attack8",
			},
			{
				triggerEventName = "attack9/begin",
				triggerDelay = 0.0,
				triggerFreeDelay = 0.0,
				effectGoName = "BUFF_bianji",
				effectAsset = {
					BundleName = "effects/prefab/buff/buff_bianji_prefab",
					AssetName = "BUFF_bianji",
				},
				playerAtTarget = false,
				referenceNodeHierarchyPath = "",
				isAttach = false,
				isRotation = false,
				triggerStopEvent = "",
				effectBtnName = "attack9",
			},
			{
				triggerEventName = "attack10/begin",
				triggerDelay = 0.0,
				triggerFreeDelay = 0.0,
				effectGoName = "chengzhujineng_htmd",
				effectAsset = {
					BundleName = "effects/prefab/misc/chengzhujineng_htmd_prefab",
					AssetName = "chengzhujineng_htmd",
				},
				playerAtTarget = false,
				referenceNodeHierarchyPath = "",
				isAttach = false,
				isRotation = false,
				triggerStopEvent = "",
				effectBtnName = "attack10",
			},
		},
		halts = {},

		sounds = {
			{
				soundEventName = "combo1_2/begin",
				soundDelay = 0.0,
				soundAudioAsset = {
					BundleName = "audios/sfxs/roleskill/role3",
					AssetName = "role3_attack1",
				},
				soundAudioGoName = "role3_attack1",
				soundIsMainRole = false,
			},
			{
				soundEventName = "combo1_1/begin",
				soundDelay = 0.0,
				soundAudioAsset = {
					BundleName = "audios/sfxs/roleskill/role3",
					AssetName = "role3_attack2",
				},
				soundAudioGoName = "role3_attack2",
				soundIsMainRole = false,
			},
			{
				soundEventName = "combo1_3/begin",
				soundDelay = 0.0,
				soundAudioAsset = {
					BundleName = "audios/sfxs/roleskill/role3",
					AssetName = "role3_attack3",
				},
				soundAudioGoName = "role3_attack3",
				soundIsMainRole = false,
			},
			{
				soundEventName = "attack3/begin",
				soundDelay = 0.0,
				soundAudioAsset = {
					BundleName = "audios/sfxs/roleskill/role3",
					AssetName = "role3_skill1",
				},
				soundAudioGoName = "role3_skill1",
				soundIsMainRole = false,
			},
			{
				soundEventName = "attack2/begin",
				soundDelay = 0.0,
				soundAudioAsset = {
					BundleName = "audios/sfxs/roleskill/role3",
					AssetName = "role3_skill2",
				},
				soundAudioGoName = "role3_skill2",
				soundIsMainRole = false,
			},
			{
				soundEventName = "attack1/begin",
				soundDelay = 0.3,
				soundAudioAsset = {
					BundleName = "audios/sfxs/roleskill/role3",
					AssetName = "role3_skill3",
				},
				soundAudioGoName = "role3_skill3",
				soundIsMainRole = false,
			},
			{
				soundEventName = "attack4/begin",
				soundDelay = 0.0,
				soundAudioAsset = {
					BundleName = "audios/sfxs/roleskill/role3",
					AssetName = "role3_skill4",
				},
				soundAudioGoName = "role3_skill4",
				soundIsMainRole = false,
			},
		},
		cameraShakes = {
			{
				CameraShakeBtnName = "技能3_轮子1",
				eventName = "attack3/begin",
				numberOfShakes = 5,
				distance = 0.15,
				speed = 100.0,
				delay = 0.3,
				decay = 0.1,
			},
			{
				CameraShakeBtnName = "技能3_轮子2",
				eventName = "attack3/begin",
				numberOfShakes = 15,
				distance = 0.25,
				speed = 100.0,
				delay = 0.85,
				decay = 0.1,
			},
			{
				CameraShakeBtnName = "技能4_轮子甩出",
				eventName = "attack4/begin",
				numberOfShakes = 17,
				distance = 0.25,
				speed = 100.0,
				delay = 0.6,
				decay = 0.1,
			},
		},
		cameraFOVs = {},

		sceneFades = {},

		footsteps = {},

	},
	actorBlinker = nil,
	TimeLineList = {},

}