return {
	actorController = {
		projectiles = {
			{
				Action = "attack11",
				HurtPosition = 0,
				Projectile = {
					BundleName = "effects/prefab/other/xiannv_qunshang_prefab",
					AssetName = "xiannv_qunshang",
				},
				ProjectilGoName = "xiannv_qunshang",
				FromPosHierarchyPath = "guadian_Head",
				DelayProjectileEff = 0.0,
				DeleProjectileDelay = 0.0,
				ProjectilNodeHierarchyPath = "",
				ProjectileBtnName = "attack11",
			},
		},
		hurts = {},

		beHurtEffecct = {},

		hurtEffectName = "",
		beHurtNodeName = "",
		beHurtAttach = false,
		hurtEffectFreeDelay = 0.0,
		QualityCtrlList = {},

	},
	actorTriggers = {
		effects = {
			{
				triggerEventName = "attack3/begin",
				triggerDelay = 0.2,
				triggerFreeDelay = 0.0,
				effectGoName = "1101_Attck4_xc_01",
				effectAsset = {
					BundleName = "effects/prefab/role/1101/1101_attck4_xc_01_prefab",
					AssetName = "1101_Attck4_xc_01",
				},
				playerAtTarget = false,
				referenceNodeHierarchyPath = "",
				isAttach = false,
				isRotation = false,
				triggerStopEvent = "",
				effectBtnName = "attack302",
			},
			{
				triggerEventName = "attack1/begin",
				triggerDelay = 0.3,
				triggerFreeDelay = 0.0,
				effectGoName = "1101_Attck1_xc",
				effectAsset = {
					BundleName = "effects/prefab/role/1101/1101_attck1_xc_prefab",
					AssetName = "1101_Attck1_xc",
				},
				playerAtTarget = false,
				referenceNodeHierarchyPath = "",
				isAttach = false,
				isRotation = false,
				triggerStopEvent = "",
				effectBtnName = "attack1",
			},
			{
				triggerEventName = "attack2/begin",
				triggerDelay = 0.5,
				triggerFreeDelay = 0.0,
				effectGoName = "1101_Attck2_xc",
				effectAsset = {
					BundleName = "effects/prefab/role/1101/1101_attck2_xc_prefab",
					AssetName = "1101_Attck2_xc",
				},
				playerAtTarget = false,
				referenceNodeHierarchyPath = "",
				isAttach = false,
				isRotation = false,
				triggerStopEvent = "",
				effectBtnName = "attack2",
			},
			{
				triggerEventName = "combo1_1/begin",
				triggerDelay = 0.2,
				triggerFreeDelay = 0.0,
				effectGoName = "W3_effect_com1",
				effectAsset = {
					BundleName = "effects/prefab/role/1101/w3_effect_com1_prefab",
					AssetName = "W3_effect_com1",
				},
				playerAtTarget = false,
				referenceNodeHierarchyPath = "",
				isAttach = false,
				isRotation = false,
				triggerStopEvent = "",
				effectBtnName = "combo1",
			},
			{
				triggerEventName = "combo1_2/begin",
				triggerDelay = 0.2,
				triggerFreeDelay = 0.0,
				effectGoName = "1101_combo_2",
				effectAsset = {
					BundleName = "effects/prefab/role/1101/1101_combo_2_prefab",
					AssetName = "1101_combo_2",
				},
				playerAtTarget = false,
				referenceNodeHierarchyPath = "",
				isAttach = false,
				isRotation = false,
				triggerStopEvent = "",
				effectBtnName = "combo2",
			},
			{
				triggerEventName = "combo1_3/begin",
				triggerDelay = 0.3,
				triggerFreeDelay = 0.0,
				effectGoName = "W3_effect_com1_3",
				effectAsset = {
					BundleName = "effects/prefab/role/1101/w3_effect_com1_3_prefab",
					AssetName = "W3_effect_com1_3",
				},
				playerAtTarget = false,
				referenceNodeHierarchyPath = "",
				isAttach = false,
				isRotation = false,
				triggerStopEvent = "",
				effectBtnName = "combo3",
			},
			{
				triggerEventName = "attack5/begin",
				triggerDelay = 0.2,
				triggerFreeDelay = 0.0,
				effectGoName = "1101001_Attack5_01_xc",
				effectAsset = {
					BundleName = "effects/prefab/role/1101/1101001_attack5_01_xc_prefab",
					AssetName = "1101001_Attack5_01_xc",
				},
				playerAtTarget = false,
				referenceNodeHierarchyPath = "",
				isAttach = false,
				isRotation = false,
				triggerStopEvent = "",
				effectBtnName = "attack5",
			},
			{
				triggerEventName = "attack4/begin",
				triggerDelay = 0.25,
				triggerFreeDelay = 0.0,
				effectGoName = "1101_Attck3_xc_01",
				effectAsset = {
					BundleName = "effects/prefab/role/1101/1101_attck3_xc_01_prefab",
					AssetName = "1101_Attck3_xc_01",
				},
				playerAtTarget = false,
				referenceNodeHierarchyPath = "",
				isAttach = false,
				isRotation = true,
				triggerStopEvent = "",
				effectBtnName = "attack4",
			},
			{
				triggerEventName = "attack3/begin",
				triggerDelay = 0.0,
				triggerFreeDelay = 0.0,
				effectGoName = "1101_Attck4_xc_02",
				effectAsset = {
					BundleName = "effects/prefab/role/1101/1101_attck4_xc_02_prefab",
					AssetName = "1101_Attck4_xc_02",
				},
				playerAtTarget = false,
				referenceNodeHierarchyPath = "",
				isAttach = false,
				isRotation = false,
				triggerStopEvent = "",
				effectBtnName = "attack3",
			},
			{
				triggerEventName = "attack6/begin",
				triggerDelay = 0.0,
				triggerFreeDelay = 0.0,
				effectGoName = "Buff_zhuahen",
				effectAsset = {
					BundleName = "effects/prefab/buff/buff_zhuahen_prefab",
					AssetName = "Buff_zhuahen",
				},
				playerAtTarget = false,
				referenceNodeHierarchyPath = "",
				isAttach = false,
				isRotation = false,
				triggerStopEvent = "",
				effectBtnName = "attack6",
			},
			{
				triggerEventName = "attack7/begin",
				triggerDelay = 0.0,
				triggerFreeDelay = 0.0,
				effectGoName = "BUFF_fuhuo",
				effectAsset = {
					BundleName = "effects/prefab/buff/buff_fuhuo_prefab",
					AssetName = "BUFF_fuhuo",
				},
				playerAtTarget = false,
				referenceNodeHierarchyPath = "",
				isAttach = false,
				isRotation = false,
				triggerStopEvent = "",
				effectBtnName = "attack7",
			},
			{
				triggerEventName = "attack8/begin",
				triggerDelay = 0.0,
				triggerFreeDelay = 0.0,
				effectGoName = "BUFF_wudi_01",
				effectAsset = {
					BundleName = "effects/prefab/buff/buff_wudi_01_prefab",
					AssetName = "BUFF_wudi_01",
				},
				playerAtTarget = false,
				referenceNodeHierarchyPath = "",
				isAttach = false,
				isRotation = false,
				triggerStopEvent = "",
				effectBtnName = "attack8",
			},
			{
				triggerEventName = "attack9/begin",
				triggerDelay = 0.0,
				triggerFreeDelay = 0.0,
				effectGoName = "BUFF_bianji",
				effectAsset = {
					BundleName = "effects/prefab/buff/buff_bianji_prefab",
					AssetName = "BUFF_bianji",
				},
				playerAtTarget = false,
				referenceNodeHierarchyPath = "",
				isAttach = false,
				isRotation = false,
				triggerStopEvent = "",
				effectBtnName = "attack9",
			},
			{
				triggerEventName = "attack10/begin",
				triggerDelay = 0.0,
				triggerFreeDelay = 0.0,
				effectGoName = "chengzhujineng_htmd",
				effectAsset = {
					BundleName = "effects/prefab/misc/chengzhujineng_htmd_prefab",
					AssetName = "chengzhujineng_htmd",
				},
				playerAtTarget = false,
				referenceNodeHierarchyPath = "",
				isAttach = false,
				isRotation = false,
				triggerStopEvent = "",
				effectBtnName = "attack10",
			},
		},
		halts = {},

		sounds = {
			{
				soundEventName = "combo1_1/begin",
				soundDelay = 0.0,
				soundAudioAsset = {
					BundleName = "audios/sfxs/roleskill/role1",
					AssetName = "role1_attack1",
				},
				soundAudioGoName = "role1_attack1",
				soundIsMainRole = false,
			},
			{
				soundEventName = "combo1_2/begin",
				soundDelay = 0.0,
				soundAudioAsset = {
					BundleName = "audios/sfxs/roleskill/role1",
					AssetName = "role1_attack2",
				},
				soundAudioGoName = "role1_attack2",
				soundIsMainRole = false,
			},
			{
				soundEventName = "combo1_3/begin",
				soundDelay = 0.0,
				soundAudioAsset = {
					BundleName = "audios/sfxs/roleskill/role1",
					AssetName = "role1_attack3",
				},
				soundAudioGoName = "role1_attack3",
				soundIsMainRole = false,
			},
			{
				soundEventName = "attack1/begin",
				soundDelay = 0.0,
				soundAudioAsset = {
					BundleName = "audios/sfxs/roleskill/role1",
					AssetName = "role1_skill1",
				},
				soundAudioGoName = "role1_skill1",
				soundIsMainRole = false,
			},
			{
				soundEventName = "attack2/begin",
				soundDelay = 0.0,
				soundAudioAsset = {
					BundleName = "audios/sfxs/roleskill/role1",
					AssetName = "role1_skill2",
				},
				soundAudioGoName = "role1_skill2",
				soundIsMainRole = false,
			},
			{
				soundEventName = "attack4/begin",
				soundDelay = 0.0,
				soundAudioAsset = {
					BundleName = "audios/sfxs/roleskill/role1",
					AssetName = "role1_skill3",
				},
				soundAudioGoName = "role1_skill3",
				soundIsMainRole = false,
			},
			{
				soundEventName = "attack3/begin",
				soundDelay = 0.1,
				soundAudioAsset = {
					BundleName = "audios/sfxs/roleskill/role1",
					AssetName = "role1_skill4",
				},
				soundAudioGoName = "role1_skill4",
				soundIsMainRole = false,
			},
		},
		cameraShakes = {
			{
				CameraShakeBtnName = "技能4_下砸抖屏",
				eventName = "attack4/begin",
				numberOfShakes = 12,
				distance = 0.2,
				speed = 100.0,
				delay = 0.5,
				decay = 0.15,
			},
			{
				CameraShakeBtnName = "技能3_第1把剑",
				eventName = "attack3/begin",
				numberOfShakes = 2,
				distance = 0.2,
				speed = 100.0,
				delay = 0.5,
				decay = 0.05,
			},
			{
				CameraShakeBtnName = "技能3_第2把剑",
				eventName = "attack3/begin",
				numberOfShakes = 0,
				distance = 0.0,
				speed = 0.0,
				delay = 0.0,
				decay = 0.0,
			},
			{
				CameraShakeBtnName = "技能3_第3把剑",
				eventName = "attack3/begin",
				numberOfShakes = 0,
				distance = 0.0,
				speed = 0.0,
				delay = 0.0,
				decay = 0.0,
			},
			{
				CameraShakeBtnName = "技能4_蓄力",
				eventName = "attack4/begin",
				numberOfShakes = 7,
				distance = 0.05,
				speed = 100.0,
				delay = 0.1,
				decay = 0.03,
			},
		},
		cameraFOVs = {},

		sceneFades = {},

		footsteps = {},

	},
	actorBlinker = nil,
	TimeLineList = {},

}