return {
	actorController = {
		projectiles = {
			{
				Action = "attack5",
				HurtPosition = 0,
				Projectile = {
					BundleName = "effects/prefab/role/1102/attack5_zidan_prefab",
					AssetName = "attack5_zidan",
				},
				ProjectilGoName = "attack5_zidan",
				FromPosHierarchyPath = "guadian_Head",
				DelayProjectileEff = 0.0,
				DeleProjectileDelay = 0.0,
				ProjectilNodeHierarchyPath = "",
				ProjectileBtnName = "按钮",
			},
			{
				Action = "attack11",
				HurtPosition = 0,
				Projectile = {
					BundleName = "effects/prefab/other/xiannv_qunshang_prefab",
					AssetName = "xiannv_qunshang",
				},
				ProjectilGoName = "xiannv_qunshang",
				FromPosHierarchyPath = "guadian_Head",
				DelayProjectileEff = 0.0,
				DeleProjectileDelay = 0.0,
				ProjectilNodeHierarchyPath = "",
				ProjectileBtnName = "attack11",
			},
		},
		hurts = {},

		beHurtEffecct = {},

		hurtEffectName = "",
		beHurtNodeName = "",
		beHurtAttach = false,
		hurtEffectFreeDelay = 0.0,
		QualityCtrlList = {},

	},
	actorTriggers = {
		effects = {
			{
				triggerEventName = "attack4/begin",
				triggerDelay = 0.0,
				triggerFreeDelay = 0.0,
				effectGoName = "1102_attack01_xc",
				effectAsset = {
					BundleName = "effects/prefab/role/1102/1102_attack01_xc_prefab",
					AssetName = "1102_attack01_xc",
				},
				playerAtTarget = false,
				referenceNodeHierarchyPath = "",
				isAttach = false,
				isRotation = true,
				triggerStopEvent = "",
				effectBtnName = "attack1",
			},
			{
				triggerEventName = "attack3/begin",
				triggerDelay = 0.0,
				triggerFreeDelay = 0.0,
				effectGoName = "1102_attack03_xc",
				effectAsset = {
					BundleName = "effects/prefab/role/1102/1102_attack03_xc_prefab",
					AssetName = "1102_attack03_xc",
				},
				playerAtTarget = false,
				referenceNodeHierarchyPath = "",
				isAttach = false,
				isRotation = false,
				triggerStopEvent = "",
				effectBtnName = "attack3",
			},
			{
				triggerEventName = "attack1/begin",
				triggerDelay = 0.1,
				triggerFreeDelay = 0.0,
				effectGoName = "1102_attack02_xc",
				effectAsset = {
					BundleName = "effects/prefab/role/1102/1102_attack02_xc_prefab",
					AssetName = "1102_attack02_xc",
				},
				playerAtTarget = false,
				referenceNodeHierarchyPath = "",
				isAttach = false,
				isRotation = true,
				triggerStopEvent = "",
				effectBtnName = "attack2",
			},
			{
				triggerEventName = "attack2/begin",
				triggerDelay = 0.1,
				triggerFreeDelay = 0.0,
				effectGoName = "1102001_attack04_xc",
				effectAsset = {
					BundleName = "effects/prefab/role/1102/1102001_attack04_xc_prefab",
					AssetName = "1102001_attack04_xc",
				},
				playerAtTarget = false,
				referenceNodeHierarchyPath = "",
				isAttach = false,
				isRotation = true,
				triggerStopEvent = "",
				effectBtnName = "attack4",
			},
			{
				triggerEventName = "combo1_1/begin",
				triggerDelay = 0.0,
				triggerFreeDelay = 0.0,
				effectGoName = "1102_effect_com1",
				effectAsset = {
					BundleName = "effects/prefab/role/1102/1102_effect_com1_prefab",
					AssetName = "1102_effect_com1",
				},
				playerAtTarget = false,
				referenceNodeHierarchyPath = "",
				isAttach = false,
				isRotation = false,
				triggerStopEvent = "",
				effectBtnName = "Combo1",
			},
			{
				triggerEventName = "combo1_2/begin",
				triggerDelay = 0.0,
				triggerFreeDelay = 0.0,
				effectGoName = "1102_effect_com2",
				effectAsset = {
					BundleName = "effects/prefab/role/1102/1102_effect_com2_prefab",
					AssetName = "1102_effect_com2",
				},
				playerAtTarget = false,
				referenceNodeHierarchyPath = "",
				isAttach = false,
				isRotation = false,
				triggerStopEvent = "",
				effectBtnName = "Combo2",
			},
			{
				triggerEventName = "combo1_3/begin",
				triggerDelay = 0.0,
				triggerFreeDelay = 0.0,
				effectGoName = "1102_effect_com3",
				effectAsset = {
					BundleName = "effects/prefab/role/1102/1102_effect_com3_prefab",
					AssetName = "1102_effect_com3",
				},
				playerAtTarget = false,
				referenceNodeHierarchyPath = "",
				isAttach = false,
				isRotation = false,
				triggerStopEvent = "",
				effectBtnName = "Combo3",
			},
			{
				triggerEventName = "attack6/begin",
				triggerDelay = 0.0,
				triggerFreeDelay = 0.0,
				effectGoName = "Buff_zhuahen",
				effectAsset = {
					BundleName = "effects/prefab/buff/buff_zhuahen_prefab",
					AssetName = "Buff_zhuahen",
				},
				playerAtTarget = false,
				referenceNodeHierarchyPath = "",
				isAttach = false,
				isRotation = false,
				triggerStopEvent = "",
				effectBtnName = "attack6",
			},
			{
				triggerEventName = "attack7/begin",
				triggerDelay = 0.0,
				triggerFreeDelay = 0.0,
				effectGoName = "BUFF_fuhuo",
				effectAsset = {
					BundleName = "effects/prefab/buff/buff_fuhuo_prefab",
					AssetName = "BUFF_fuhuo",
				},
				playerAtTarget = false,
				referenceNodeHierarchyPath = "",
				isAttach = false,
				isRotation = false,
				triggerStopEvent = "",
				effectBtnName = "attack7",
			},
			{
				triggerEventName = "attack8/begin",
				triggerDelay = 0.0,
				triggerFreeDelay = 0.0,
				effectGoName = "BUFF_wudi_01",
				effectAsset = {
					BundleName = "effects/prefab/buff/buff_wudi_01_prefab",
					AssetName = "BUFF_wudi_01",
				},
				playerAtTarget = false,
				referenceNodeHierarchyPath = "",
				isAttach = false,
				isRotation = false,
				triggerStopEvent = "",
				effectBtnName = "attack8",
			},
			{
				triggerEventName = "attack9/begin",
				triggerDelay = 0.0,
				triggerFreeDelay = 0.0,
				effectGoName = "BUFF_bianji",
				effectAsset = {
					BundleName = "effects/prefab/buff/buff_bianji_prefab",
					AssetName = "BUFF_bianji",
				},
				playerAtTarget = false,
				referenceNodeHierarchyPath = "",
				isAttach = false,
				isRotation = false,
				triggerStopEvent = "",
				effectBtnName = "attack9",
			},
			{
				triggerEventName = "attack10/begin",
				triggerDelay = 0.0,
				triggerFreeDelay = 0.0,
				effectGoName = "chengzhujineng_htmd",
				effectAsset = {
					BundleName = "effects/prefab/misc/chengzhujineng_htmd_prefab",
					AssetName = "chengzhujineng_htmd",
				},
				playerAtTarget = false,
				referenceNodeHierarchyPath = "",
				isAttach = false,
				isRotation = false,
				triggerStopEvent = "",
				effectBtnName = "attack10",
			},
		},
		halts = {},

		sounds = {
			{
				soundEventName = "combo1_1/begin",
				soundDelay = 0.0,
				soundAudioAsset = {
					BundleName = "audios/sfxs/roleskill/role2",
					AssetName = "role2_attack1",
				},
				soundAudioGoName = "role2_attack1",
				soundIsMainRole = false,
			},
			{
				soundEventName = "combo1_2/begin",
				soundDelay = 0.0,
				soundAudioAsset = {
					BundleName = "audios/sfxs/roleskill/role2",
					AssetName = "role2_attack2",
				},
				soundAudioGoName = "role2_attack2",
				soundIsMainRole = false,
			},
			{
				soundEventName = "combo1_3/begin",
				soundDelay = 0.0,
				soundAudioAsset = {
					BundleName = "audios/sfxs/roleskill/role2",
					AssetName = "role2_attack3",
				},
				soundAudioGoName = "role2_attack3",
				soundIsMainRole = false,
			},
			{
				soundEventName = "attack1/begin",
				soundDelay = 0.1,
				soundAudioAsset = {
					BundleName = "audios/sfxs/roleskill/role2",
					AssetName = "role2_skill1",
				},
				soundAudioGoName = "role2_skill1",
				soundIsMainRole = false,
			},
			{
				soundEventName = "attack4/begin",
				soundDelay = 0.0,
				soundAudioAsset = {
					BundleName = "audios/sfxs/roleskill/role2",
					AssetName = "role2_skill4",
				},
				soundAudioGoName = "role2_skill4",
				soundIsMainRole = false,
			},
			{
				soundEventName = "attack3/begin",
				soundDelay = 0.15,
				soundAudioAsset = {
					BundleName = "audios/sfxs/roleskill/role2",
					AssetName = "role2_skill3",
				},
				soundAudioGoName = "role2_skill3",
				soundIsMainRole = false,
			},
			{
				soundEventName = "attack2/begin",
				soundDelay = 0.0,
				soundAudioAsset = {
					BundleName = "audios/sfxs/roleskill/role2",
					AssetName = "role2_skill2",
				},
				soundAudioGoName = "role2_skill2",
				soundIsMainRole = false,
			},
		},
		cameraShakes = {
			{
				CameraShakeBtnName = "技能2_冰块砸地",
				eventName = "attack2/begin",
				numberOfShakes = 10,
				distance = 0.25,
				speed = 100.0,
				delay = 1.0,
				decay = 0.2,
			},
		},
		cameraFOVs = {},

		sceneFades = {},

		footsteps = {},

	},
	actorBlinker = {
		blinkFadeIn = 0.0,
		blinkFadeHold = 0.0,
		blinkFadeOut = 0.0,
	},
	TimeLineList = {},

}