return {
	id = 3012,
	name = "冰龙谷十二层",
	scene_type = 68,
	bundle_name = "scenes/map/w3_yw_bingxue_main",
	asset_name = "W3_YW_BingXue_Main",
	width = 128,
	height = 129,
	origin_x = 96,
	origin_y = 178,
	levellimit = 0,
    is_forbid_pk = 0,
    skip_loading = 0,
	show_weather = 0,
    scenex = 67,
    sceney = 93,
	npcs = {
	},
	monsters = {
	},
	doors = {
	},
    gathers = {
	},
    jumppoints = {
    },
    fences = {
	},
    effects = {
		{bundle="effects/prefab/misc/zudang_xue_prefab", asset="zudang_xue.prefab", offset={0, 0, 0}, rotation={0, 90, 0}, scale={1, 1, 1}, x=112, y=48},
		{bundle="effects/prefab/misc/zudang_xue_prefab", asset="zudang_xue.prefab", offset={0, 0, 0}, rotation={0, 0, 0}, scale={1, 1, 1}, x=67, y=115},
		{bundle="effects/prefab/misc/zudang_xue_prefab", asset="zudang_xue.prefab", offset={0, 0, 0}, rotation={0, 0, 0}, scale={1, 1, 1}, x=76, y=115},
		{bundle="effects/prefab/misc/zudang_xue_prefab", asset="zudang_xue.prefab", offset={0, 0, 0}, rotation={0, 0, 0}, scale={1, 1, 1}, x=86, y=115},
		{bundle="effects/prefab/misc/zudang_xue_prefab", asset="zudang_xue.prefab", offset={0, 0, 0}, rotation={0, 0, 0}, scale={1, 1, 1}, x=96, y=115},
		{bundle="effects/prefab/ui_x/effect_jiantou_dc_prefab", asset="effect_jiantou_dc.prefab", offset={0, 0, 0}, rotation={0, -90, 0}, scale={1, 1, 1}, x=70, y=70},
		{bundle="effects/prefab/ui_x/effect_jiantou_dc_prefab", asset="effect_jiantou_dc.prefab", offset={0, 0, 0}, rotation={0, -90, 0}, scale={1, 1, 1}, x=70, y=74},
		{bundle="effects/prefab/ui_x/effect_jiantou_dc_prefab", asset="effect_jiantou_dc.prefab", offset={0, 0, 0}, rotation={0, -180, 0}, scale={1, 1, 1}, x=70, y=77},
		{bundle="effects/prefab/ui_x/effect_jiantou_dc_prefab", asset="effect_jiantou_dc.prefab", offset={0, 0, 0}, rotation={0, -180, 0}, scale={1, 1, 1}, x=66, y=77},
		{bundle="effects/prefab/ui_x/effect_jiantou_dc_prefab", asset="effect_jiantou_dc.prefab", offset={0, 0, 0}, rotation={0, -180, 0}, scale={1, 1, 1}, x=62, y=77},
		{bundle="effects/prefab/ui_x/effect_jiantou_dc_prefab", asset="effect_jiantou_dc.prefab", offset={0, 0, 0}, rotation={0, 90, 0}, scale={1, 1, 1}, x=58, y=78},
		{bundle="effects/prefab/ui_x/effect_jiantou_dc_prefab", asset="effect_jiantou_dc.prefab", offset={0, 0, 0}, rotation={0, 90, 0}, scale={1, 1, 1}, x=58, y=74},
		{bundle="effects/prefab/ui_x/effect_jiantou_dc_prefab", asset="effect_jiantou_dc.prefab", offset={0, 0, 0}, rotation={0, -90, 0}, scale={1, 1, 1}, x=70, y=66},
		{bundle="effects/prefab/ui_x/effect_jiantou_dc_prefab", asset="effect_jiantou_dc.prefab", offset={0, 0, 0}, rotation={0, 90, 0}, scale={1, 1, 1}, x=58, y=70},
		{bundle="effects/prefab/ui_x/effect_jiantou_dc_prefab", asset="effect_jiantou_dc.prefab", offset={0, 0, 0}, rotation={0, 90, 0}, scale={1, 1, 1}, x=58, y=67},
		{bundle="effects/prefab/ui_x/effect_jiantou_dc_prefab", asset="effect_jiantou_dc.prefab", offset={0, 0, 0}, rotation={0, 90, 0}, scale={1, 1, 1}, x=58, y=63},
		{bundle="effects/prefab/ui_x/effect_jiantou_dc_prefab", asset="effect_jiantou_dc.prefab", offset={0, 0, 0}, rotation={0, 0, 0}, scale={1, 1, 1}, x=58, y=57},
		{bundle="effects/prefab/ui_x/effect_jiantou_dc_prefab", asset="effect_jiantou_dc.prefab", offset={0, 0, 0}, rotation={0, 0, 0}, scale={1, 1, 1}, x=62, y=57},
		{bundle="effects/prefab/ui_x/effect_jiantou_dc_prefab", asset="effect_jiantou_dc.prefab", offset={0, 0, 0}, rotation={0, 0, 0}, scale={1, 1, 1}, x=67, y=57},
		{bundle="effects/prefab/ui_x/effect_jiantou_dc_prefab", asset="effect_jiantou_dc.prefab", offset={0, 0, 0}, rotation={0, 0, 0}, scale={1, 1, 1}, x=73, y=57},
		{bundle="effects/prefab/ui_x/effect_jiantou_dc_prefab", asset="effect_jiantou_dc.prefab", offset={0, 0, 0}, rotation={0, -90, 0}, scale={1, 1, 1}, x=79, y=63},
		{bundle="effects/prefab/ui_x/effect_jiantou_dc_prefab", asset="effect_jiantou_dc.prefab", offset={0, 0, 0}, rotation={0, -90, 0}, scale={1, 1, 1}, x=79, y=67},
		{bundle="effects/prefab/ui_x/effect_jiantou_dc_prefab", asset="effect_jiantou_dc.prefab", offset={0, 0, 0}, rotation={0, -90, 0}, scale={1, 1, 1}, x=79, y=72},
		{bundle="effects/prefab/ui_x/effect_jiantou_dc_prefab", asset="effect_jiantou_dc.prefab", offset={0, 0, 0}, rotation={0, -90, 0}, scale={1, 1, 1}, x=79, y=77},
		{bundle="effects/prefab/ui_x/effect_jiantou_dc_prefab", asset="effect_jiantou_dc.prefab", offset={0, 0, 0}, rotation={0, -90, 0}, scale={1, 1, 1}, x=79, y=82},
		{bundle="effects/prefab/ui_x/effect_jiantou_dc_prefab", asset="effect_jiantou_dc.prefab", offset={0, 0, 0}, rotation={0, -180, 0}, scale={1, 1, 1}, x=77, y=84},
		{bundle="effects/prefab/ui_x/effect_jiantou_dc_prefab", asset="effect_jiantou_dc.prefab", offset={0, 0, 0}, rotation={0, -180, 0}, scale={1, 1, 1}, x=72, y=84},
		{bundle="effects/prefab/ui_x/effect_jiantou_dc_prefab", asset="effect_jiantou_dc.prefab", offset={0, 0, 0}, rotation={0, -180, 0}, scale={1, 1, 1}, x=67, y=84},
		{bundle="effects/prefab/ui_x/effect_jiantou_dc_prefab", asset="effect_jiantou_dc.prefab", offset={0, 0, 0}, rotation={0, -180, 0}, scale={1, 1, 1}, x=62, y=84},
		{bundle="effects/prefab/ui_x/effect_jiantou_dc_prefab", asset="effect_jiantou_dc.prefab", offset={0, 0, 0}, rotation={0, -180, 0}, scale={1, 1, 1}, x=58, y=84},
		{bundle="effects/prefab/ui_x/effect_jiantou_dc_prefab", asset="effect_jiantou_dc.prefab", offset={0, 0, 0}, rotation={0, 90, 0}, scale={1, 1, 1}, x=54, y=84},
		{bundle="effects/prefab/ui_x/effect_jiantou_dc_prefab", asset="effect_jiantou_dc.prefab", offset={0, 0, 0}, rotation={0, 90, 0}, scale={1, 1, 1}, x=54, y=79},
		{bundle="effects/prefab/ui_x/effect_jiantou_dc_prefab", asset="effect_jiantou_dc.prefab", offset={0, 0, 0}, rotation={0, 90, 0}, scale={1, 1, 1}, x=54, y=75},
		{bundle="effects/prefab/ui_x/effect_jiantou_dc_prefab", asset="effect_jiantou_dc.prefab", offset={0, 0, 0}, rotation={0, 90, 0}, scale={1, 1, 1}, x=54, y=70},
		{bundle="effects/prefab/ui_x/effect_jiantou_dc_prefab", asset="effect_jiantou_dc.prefab", offset={0, 0, 0}, rotation={0, 90, 0}, scale={1, 1, 1}, x=54, y=67},
		{bundle="effects/prefab/ui_x/effect_jiantou_dc_prefab", asset="effect_jiantou_dc.prefab", offset={0, 0, 0}, rotation={0, 90, 0}, scale={1, 1, 1}, x=54, y=63},
		{bundle="effects/prefab/ui_x/effect_jiantou_dc_prefab", asset="effect_jiantou_dc.prefab", offset={0, 0, 0}, rotation={0, 90, 0}, scale={1, 1, 1}, x=54, y=59},
		{bundle="effects/prefab/ui_x/effect_jiantou_dc_prefab", asset="effect_jiantou_dc.prefab", offset={0, 0, 0}, rotation={0, 0, 0}, scale={1, 1, 1}, x=56, y=48},
		{bundle="effects/prefab/ui_x/effect_jiantou_dc_prefab", asset="effect_jiantou_dc.prefab", offset={0, 0, 0}, rotation={0, 0, 0}, scale={1, 1, 1}, x=61, y=48},
		{bundle="effects/prefab/ui_x/effect_jiantou_dc_prefab", asset="effect_jiantou_dc.prefab", offset={0, 0, 0}, rotation={0, 0, 0}, scale={1, 1, 1}, x=66, y=48},
		{bundle="effects/prefab/ui_x/effect_jiantou_dc_prefab", asset="effect_jiantou_dc.prefab", offset={0, 0, 0}, rotation={0, 0, 0}, scale={1, 1, 1}, x=71, y=48},
		{bundle="effects/prefab/ui_x/effect_jiantou_dc_prefab", asset="effect_jiantou_dc.prefab", offset={0, 0, 0}, rotation={0, 0, 0}, scale={1, 1, 1}, x=75, y=48},
		{bundle="effects/prefab/ui_x/effect_jiantou_dc_prefab", asset="effect_jiantou_dc.prefab", offset={0, 0, 0}, rotation={0, 0, 0}, scale={1, 1, 1}, x=81, y=48},
		{bundle="effects/prefab/ui_x/effect_jiantou_dc_prefab", asset="effect_jiantou_dc.prefab", offset={0, 0, 0}, rotation={0, 0, 0}, scale={1, 1, 1}, x=87, y=48},
		{bundle="effects/prefab/ui_x/effect_jiantou_dc_prefab", asset="effect_jiantou_dc.prefab", offset={0, 0, 0}, rotation={0, 0, 0}, scale={1, 1, 1}, x=93, y=48},
		{bundle="effects/prefab/ui_x/effect_jiantou_dc_prefab", asset="effect_jiantou_dc.prefab", offset={0, 0, 0}, rotation={0, 0, 0}, scale={1, 1, 1}, x=99, y=48},
		{bundle="effects/prefab/ui_x/effect_jiantou_dc_prefab", asset="effect_jiantou_dc.prefab", offset={0, 0, 0}, rotation={0, 0, 0}, scale={1, 1, 1}, x=104, y=48},
		{bundle="effects/prefab/ui_x/effect_jiantou_dc_prefab", asset="effect_jiantou_dc.prefab", offset={0, 0, 0}, rotation={0, 0, 0}, scale={1, 1, 1}, x=109, y=48},
		{bundle="effects/prefab/ui_x/effect_jiantou_dc_prefab", asset="effect_jiantou_dc.prefab", offset={0, 0, 0}, rotation={0, 90, 0}, scale={1, 1, 1}, x=54, y=55},
		{bundle="effects/prefab/ui_x/effect_jiantou_dc_prefab", asset="effect_jiantou_dc.prefab", offset={0, 0, 0}, rotation={0, 90, 0}, scale={1, 1, 1}, x=54, y=50},
		{bundle="effects/prefab/ui_x/effect_jiantou_dc_prefab", asset="effect_jiantou_dc.prefab", offset={0, 0, 0}, rotation={0, 0, 0}, scale={1, 1, 1}, x=77, y=57},
		{bundle="effects/prefab/ui_x/effect_jiantou_dc_prefab", asset="effect_jiantou_dc.prefab", offset={0, 0, 0}, rotation={0, -90, 0}, scale={1, 1, 1}, x=79, y=58},
	},
    mask = "XQAAQAAAAG/9//+jt/9HPkgVcjlhUbiSKOZw9Zl9Mi4Huvt9S7SQaboNBFMOueFekClsGcPeNNbO99QfCwFaYz6T/3XrE6BaaMB54k8pJ/gOh/J1VUjTYUllKyL4i8WVYDr1zPt+BWu7zMQlcr36UjrMB+zSVJEWrUvV/xDtjMO0yRl8MMAP8l2s1CKA6+XWdxjn+AC0bcfw5yrZfwcpf2MCwF5wX6Ff0xrZLq33hzEdNhAcQFlSyTcPqdGPM/y9SUdMQvm2L3dyCdCU/6uAM3BP1J4SwFU+jw5/BFoddldD0vHaseHo5DDhvCM8aiEww7dtZ0u/2kle///3Qp3/",
}