-- T-推送配置.xls
return {
notification={
{},
{hour=15,},
{hour=16,title="跨服钓鱼",content="一曲高歌一樽酒，一人独钓一江秋。",},
{hour=18,title="温泉答题",content="温泉时间到，众仙女等你宽衣共浴呢！",},
{hour=19,title="双倍护送",content="双倍护送已开启，海量经验等你来领~",},
{hour=20,title="战场活动",content="群雄逐鹿，决战天下",},
{weekday=2,},
{weekday=2,hour=15,},
{weekday=2,hour=16,title="跨服钓鱼",content="一曲高歌一樽酒，一人独钓一江秋。",},
{weekday=2,hour=18,title="温泉答题",content="温泉时间到，众仙女等你宽衣共浴呢！",},
{weekday=2,hour=19,title="双倍护送",content="双倍护送已开启，海量经验等你来领~",},
{weekday=2,hour=20,title="仙盟抢旗",content="剑如霜，马长嘶！全盟集结！抢旗！",},
{weekday=3,},
{weekday=3,hour=15,},
{weekday=3,hour=16,title="跨服钓鱼",content="一曲高歌一樽酒，一人独钓一江秋。",},
{weekday=3,hour=18,title="温泉答题",content="温泉时间到，众仙女等你宽衣共浴呢！",},
{weekday=3,hour=19,title="双倍护送",content="双倍护送已开启，海量经验等你来领~",},
{weekday=3,hour=20,title="攻城之战",content="狼烟起，烽火燃！全盟集结！夺城！",},
{weekday=4,},
{weekday=4,hour=15,},
{weekday=4,hour=16,title="跨服钓鱼",content="一曲高歌一樽酒，一人独钓一江秋。",},
{weekday=4,hour=18,title="温泉答题",content="温泉时间到，众仙女等你宽衣共浴呢！",},
{weekday=4,hour=19,title="双倍护送",content="双倍护送已开启，海量经验等你来领~",},
{weekday=4,hour=20,title="战场活动",content="群雄逐鹿，决战天下",},
{weekday=5,},
{weekday=5,hour=15,},
{weekday=5,hour=16,title="跨服钓鱼",content="一曲高歌一樽酒，一人独钓一江秋。",},
{weekday=5,hour=18,title="温泉答题",content="温泉时间到，众仙女等你宽衣共浴呢！",},
{weekday=5,hour=19,title="双倍护送",content="双倍护送已开启，海量经验等你来领~",},
{weekday=5,hour=20,title="仙盟抢旗",content="剑如霜，马长嘶！全盟集结！抢旗！",},
{weekday=6,},
{weekday=6,hour=15,},
{weekday=6,hour=16,title="跨服钓鱼",content="一曲高歌一樽酒，一人独钓一江秋。",},
{weekday=6,hour=18,title="温泉答题",content="温泉时间到，众仙女等你宽衣共浴呢！",},
{weekday=6,hour=19,title="双倍护送",content="双倍护送已开启，海量经验等你来领~",},
{weekday=6,hour=20,title="战场活动",content="群雄逐鹿，决战天下",},
{weekday=7,},
{weekday=7,hour=15,},
{weekday=7,hour=16,title="跨服钓鱼",content="一曲高歌一樽酒，一人独钓一江秋。",},
{weekday=7,hour=18,title="温泉答题",content="温泉时间到，众仙女等你宽衣共浴呢！",},
{weekday=7,hour=19,title="双倍护送",content="双倍护送已开启，海量经验等你来领~",},
{weekday=7,hour=20,title="攻城之战",content="狼烟起，烽火燃！全盟集结！夺城！",}},

notification_default_table={weekday=1,hour=11,minute=0,second=0,title="世界BOSS",content="世界BOSS降临，大家赶紧行动吧！",}

}

