ViewName = {
	ArenaRankView = "ArenaRankView",				-- 竞技场统计
	TipsEnterArenaView = "TipsEnterArenaView",		-- 竞技场tips
	ArenaActivityView = "ArenaActivityView",		-- 竞技场主面板
	KFArenaActivityView = "KFArenaActivityView",	-- 跨服竞技场主面板
	Agent = "Agent",								-- 登陆SDK
	BagRecycle = "BagRecycle",						-- 装备回收，精灵回收
	-- Compose = "Compose",							-- 炼炉
	Login = "Login",								-- 登录
	Main = "Main",									-- 主界面
	MainUIResIconList = "MainUIResIconList",		-- 主界面图标列表
	MainUIActivityPreview = "MainUIActivityPreview",-- 主界面活动预览
	AttackMode = "AttackMode",						-- 攻击模式界面
	Chat = "Chat",									-- 聊天面板
	VoiceSetting = "VoiceSetting",					-- 语音设置
	CoolChat = "CoolChat",							-- 炫酷聊天面板
	TaskDialog = "TaskDialog",						-- 任务对话框
	Player = "Player",								-- 角色面板
	Market = "Market",								-- 市场
	Forge = "Forge",								-- 锻造
	ForgeJadeBag = "ForgeJadeBag",					-- 锻造玉石背包
	ForgeJadeBagFenJie = "ForgeJadeBagFenJie",		-- 锻造玉石分解
	ForgeConvertJade = "ForgeConvertJade",			-- 玉石兑换
	EquipmentShen = "EquipmentShen",				-- 神装
	AppearanceView = "AppearanceView",				-- 外观
	MultiMountHuanHua = "MultiMountHuanHua", 		-- 双人坐骑幻化
	TouShiHuanHua = "TouShiHuanHua",				-- 头饰幻化面板
	MaskHuanHua = "MaskHuanHuaView",				-- 面饰幻化
	WaistHuanHua = "WaistHuanHua",					-- 腰饰幻化面板
	QilinBiHuanHua = "QilinBiHuanHua",				-- 麒麟臂幻化面板
	LingZhuHuanHua = "LingZhuHuanHua",				-- 灵珠幻化面板
	XianBaoHuanHua = "XianBaoHuanHua", 				-- 仙宝幻化面板
	LingChongHuanHua = "LingChongHuanHua",			-- 灵童幻化面板
	LingGongHuanHua = "LingGongHuanHua",			-- 灵弓幻化面板
	LingQiHuanHua = "LingQiHuanHua",				-- 灵骑幻化面板
	WeiYanHuanHua = "WeiYanHuanHua",				-- 尾焰幻化面板
	ShouHuanHuanHua = "ShouHuanHuanHua",			-- 手环幻化面板
	TailHuanHua = "TailHuanHua",					-- 尾巴幻化面板
	FlyPetHuanHua = "FlyPetHuanHua",				-- 飞宠幻化面板
	BianShenView = "BianShenView",					-- 仙域-变身
	MythView = "MythView",							-- 神话	
	TianshenhutiView = "TianshenhutiView",			-- 无双装备	
	TipsFamousSkillView = "TipsFamousSkillView", 	-- 变身技能属性界面
	BianShenWarehouseView = "BianShenWarehouseView",	-- 变身-请神-仓库
	BianShenEquipBag = "BianShenEquipBag",			--变身装备仓库
	BianShenStrengthenSelectView = "BianShenStrengthenSelectView", -- 变身强化，挑选视图
	BianShenSkillTipView = "BianShenSkillTipView",	-- 变身技能信息视图
	GaoZhanFuBen = "GaoZhanView",					-- 高战副本
	TowerRank = "TowerRankView",					-- 爬塔排行榜
	GuildMijingFightView = "GuildMijingFightView",	-- 行会秘境
	GuildMijingFinishRewardView = "GuildMijingFinishRewardView",	-- 试炼结束
	Boss = "Boss",									-- BOSS
	TipsPowerChangeView = "TipsPowerChangeView",	-- 战斗力变化
	Warehouse = "Warehouse",						-- 仓库面板
	BaoJu = "BaoJu",								-- 宝具面板
	ZhiBaoHuanhua = "ZhiBaoHuanhua",				-- 至宝幻化面板
	Advance = "Advance",							-- 进阶面板
	MarriageWedding = "MarriageWeddingView",		-- 婚宴面板
	MarryNpcMe = "MarryNpcMe",						-- 月老面板
	-- AdvanceEquipUp = "AdvanceEquipUp",			-- 进阶装备升级面板
	MountHuanHua = "MountHuanHua",					-- 幻化面板
	ClearBlessTipView = "ClearBlessTipView",		-- 进阶幸运值清空提示界面
	AdvanceHuanhua = "AdvanceHuanhua",				-- 形象幻化面板
	WingHuanHua = "WingHuanHua",					-- 羽翼幻化面板
	ShenCiMountHuanHua = "ShenCiMountHuanHua",		-- 神赐坐骑幻化面板
	ShenCiWingHuanHua = "ShenCiWingHuanHua",		-- 神赐羽翼幻化面板
	ShenCiFightMountHuanHua = "ShenCiFightMountHuanHua",		-- 神赐战骑幻化面板
	HaloHuanHua = "HaloHuanHua",					-- 光环幻化面板
	FaBaoHuanHua = "FaBaoHuanHua",					-- 法宝幻化面板
	ShengongHuanHua = "ShengongHuanHua",			-- 神弓幻化面板
	ShenyiHuanHua = "ShenyiHuanHua",				-- 神翼幻化面板
	FootHuanHua = "FootHuanHua",					-- 足迹幻化面板
	FashionHuanhua = "FashionHuanhua",				-- 时装进阶(幻化)面版
	WuQiHuanHuaView = "WuQiHuanHuaView",            -- 武器（神兵）幻化面板 
	FightMountHuanHua = "FightMountHuanHua",		-- 战斗坐骑幻化面板
	ImageFuLing = "ImageFuLing",					-- 形象附灵
	TalentBagView = "TalentBagView",				-- 天赋背包
	TalentUpgradeView = "TalentUpgradeView",		-- 天赋升级界面
	TalentSkillUpgradeView = "TalentSkillUpgradeView",--天赋技能升级界面
	ImageFulingWindowView = "ImageFulingWindowView",-- 形象赋灵弹窗
	WakeUpFocusView = "WakeUpFocusView",
	Goddess = "Goddess",							-- 女神面板
	GoddessHuanHua = "GoddessHuanHua",				-- 女神幻化面板
	Answer = "Answer",								-- 答题面板
	Guild = "Guild",								-- 公会面板
	GuildWageView = "GuildWageView",				-- 仙盟工资面板
	GuildRedPacket = "GuildRedPacket",				-- 公会红包
	ZhiZunRechargeRankView = "ZhiZunRechargeRankView",-- 至尊充值
	Welfare = "Welfare",							-- 福利面板
	SpiritGetSkillView = "SpiritGetSkillView",		-- 精灵技能获取面板
	OffLineExp = "OffLineExp",						-- 离线经验面板
	OnLineReward = "OnLineReward",					-- 在线奖励面板
	TipChengZhang = "TipChengZhang",				-- 成长丹提示框
	TipZiZhi = "TipZiZhi",							-- 资质丹提示框
	TipSkillUpgrade = "TipSkillUpgrade",			-- 进阶技能提示框
	TipXunZhangView = "TipXunZhangView",			-- 进阶勋章提示框
	Ranking = "RankingView",						-- 排行榜面板
	CrossRankView = "CrossRankView",				-- 跨服排行榜面板
	FuBen = "FuBen",								-- 副本面板
	Scoiety = "Scoiety",							-- 社交面板
	SendGiftView = "SendGiftView",					-- 送礼面板
	SendGiftSelectView = "SendGiftSelectView",		-- 送礼选择面板			
	FriendRec = "FriendRec",						-- 好友推荐面板
	CheckEquip = "CheckView",						-- 查看面板
	NearTeamView = "NearTeamView",					-- 附近队伍
	InviteView = "InviteView",						-- 邀请
	BlackView = "BlackView",						-- 黑名单
	ScratchTicketView = "ScratchTicketView",		-- 刮刮乐
	FriendListView = "FriendListView",				-- 好友列表
	GiftRecord = "GiftRecord",						-- 收礼记录
	FriendDeleteView = "FriendDeleteView",			-- 批量删除好友
	ApplyView = "ApplyView",						-- 请求列表
	OperateList = "OperateList",					-- 玩家操作列表
	Compose = "ComposeView",						-- 合成面板
	EuropeanWeddingTips = "EuropeanWeddingTips",	-- 西式婚礼提示框
	ExpenseNiceGiftRewardPool = "ExpenseNiceGiftRewardPool",	--消费好礼（奖励池）面板
	Activity = "Activity",							-- 活动总面板
	ActivityDetail = "ActivityDetail",				-- 活动详情面板
	GuildFight = "GuildFight",						-- 公会争霸面板
	GuildFightRankView = "GuildFightRankView",		-- 公会争霸排行面板
	DaFuHao = "DaFuHao",							-- 富豪转盘面板
	DaFuHaoRoll = "DaFuHaoRoll",					-- 大富豪转盘
	Exchange = "NewExchangeView",					-- 兑换面板
	YiHuoExchange = "YiHuoExchange",				-- 异火兑换
	YuShiExchangeView = "YuShiExchangeView", 		-- 玉石兑换面板
	FBInfoView = "FBInfoView",						-- 副本信息面板
	FBFinishStarView = "FBFinishStarView",			-- 副本星级胜利
	FBVictoryFinishView = "FBVictoryFinishView",	-- 副本胜利结束面板
	FBFailFinishView = "FBFailFinishView",			-- 副本失败结束面板
	FBAddFriendView = "FBAddFriendView",			-- 副本结束加好友面板
	FBFinishView = "FBFinishView",					-- 武器材料结束面板
	Shop = "ShopView",								-- 商城面板
	Setting = "SettingView",						-- 设置面板
	Unlock = "UnlockView",							-- 锁屏面板
	SettingSkill = "SettingSkill",					-- 设置技能面板
	Treasure = "Treasure",							-- 寻宝面板
	TreasureReward = "TreasureReward",				-- 寻宝奖励面板
	TradeView = "TradeView",						-- 交易面板
	Map = "Map",									-- 地图面板
	Marriage = "Marriage",							-- 结婚面板
	MarryBaby = "MarryBaby",						-- 宝宝面板
	ReminderGetBaobaoView = "ReminderGetBaobaoView",-- 获取宝宝面板
	LittlePetView = "LittlePetView",				-- 小宠物面板
	WeddingEnterView = "WeddingEnterView",			-- 婚宴进入面板
	WeddingYuYueView = "WeddingYuYueView",			-- 婚宴预约面板
	WeddingInviteView = "WeddingInviteView",		-- 婚宴邀请面板
	WeddingHunShuView = "WeddingHunShuView",		-- 求婚按手印面板
	WeddingDeMandView = "WeddingDeMandView",		-- 婚宴请帖
	WeddingBlessView = "WeddingBlessView",			-- 祝福面板
	Church = "Church",								-- 教堂面板
	Wedding = "Wedding",							-- 求婚面板
	GiftEffectView = "GiftEffectView",				-- 表白特效面板
	ReviveView = "ReviveView",						-- 复活面板
	CommonTips = "CommonTips",						-- 公共提示
	ShengHunView = "ShengHunView",					-- 圣魂面板
	KuaFuFuBenView = "KuaFuFuBenView",				-- 跨服副本面板
	FuBenPhaseInfoView = "FuBenPhaseInfoView",		-- 进阶副本信息面板
	FuBenExpInfoView = "FuBenExpInfoView",			-- 经验副本信息面板
	FuBenStoryInfoView = "FuBenStoryInfoView",		-- 剧情副本信息面板
	FuBenVipInfoView = "FuBenVipInfoView",			-- VIP副本信息面板
	FuBenTowerInfoView = "FuBenTowerInfoView",		-- 爬塔副本信息面板
	TowerRewardInfoShowTips = "TowerRewardInfoShowTips",		-- 爬塔解锁提示
	TowerMoJieView = "TowerMoJieView", 				-- 爬塔魔戒/仙戒面板
	FuBenHunYanInfoView = "FuBenHunYanInfoView",	-- 婚宴副本信息面板
	FuBenQingYuanInfoView = "FuBenQingYuanInfoView",-- 情缘副本信息面板
	FuBenShengDiInfoView = "FuBenShengDiInfoView",	-- 圣地副本信息面板
	FuBenGuardInfoView = "FuBenGuardInfoView",		-- 个人塔防副本信息面板
	FuBenQualityInfoView = "FuBenQualityInfoView",	-- 品质副本信息面板
	FuBenPushInfoView = "FuBenPushInfoView",		-- 推图副本信息面板
	FuBenArmorInfoView = "FuBenArmorInfoView",		-- 防具材料副本信息面板
	FuBenWeaponInfoView = "FuBenWeaponInfoView",	-- 武器材料副本信息面板
	FuBenDefenseInfoView = "FuBenDefenseInfoView",	-- 塔防副本信息面板(建塔)
	FuBenTowerSelectView = "FuBenTowerSelectView",	-- 组队守护选中职业面板
	FuBenTowerSkillView = "FuBenTowerSkillView",	-- 组队守护技能面板
	FuBenTeamInfoView = "FuBenTeamInfoView",		-- 组队守护信息面板
	FuBenSpecialInfoView = "FuBenSpecialInfoView",	-- 组队爬塔信息面板
	FuBenTeamSkillExplain = "FuBenTeamSkillExplain",-- 组队守护技能介绍面板
	PhaseSaoDangView = "PhaseSaoDangView",			-- 进阶副本扫荡界面
	SpiritView = "SpiritView",						-- 仙宠面板
	SpiritHuanHuaView = "SpiritHuanHuaView",		-- 仙宠幻化面板
	SpiritWarehouseView = "SpiritWarehouseView",	-- 仙宠-猎取-仓库
	SpiritWuxingdanBuyView = "SpiritWuxingdanBuyView",-- 仙宠-悟性丹收购
	SpiritExchangeView = "SpiritExchangeView",		-- 仙宠-猎取-兑换
	SpiritTujian = "SpiritTujian",					-- 仙宠-猎取-仙宠图鉴
	SpiritSoulResolveView = "SpiritSoulResolveView",-- 仙宠灵魂分解
	SpiriBigSkillView = "SpiriBigSkillView", 		-- 仙宠技能-技能获取

	VipView = "VipView",							-- Vip面板
	WangZheZhiJieView = "WangZheZhiJieView",		-- 王者之戒
	ZhiZunLingPaiView = "ZhiZunLingPaiView",		-- 至尊令牌
	CrossButtonView = "CrossButtonView",			-- 跨服组队求救按钮
	KuaFu1v1 = "KuaFu1v1",							-- 跨服1v1
	KuaFu1v1Rank = "KuaFu1v1Rank",					-- 跨服1v1排行榜
	KuaFu1v1Grade = "KuaFu1v1Grade",				-- 跨服1v1段位奖励
	KuaFu1v1Count = "KuaFu1v1Count",				-- 跨服1v1匹配
	KuaFu1v1PiPei = "KuaFu1v1PiPei",				-- 跨服1v1匹配
	KuaFuConsumeRank = "KuaFuConsumeRank",			-- 跨服消费排行榜
	ZhiZunLingPai = "ZhiZunLingPai",				-- 至尊令牌
	DaLeGouView = "DaLeGouView",					-- 大乐购
	DaLeGouTips = "DaLeGouTips",
	KuaFu3v3 = "KFPVPView",							-- 跨服3v3
	KFPVPViewPiPei = "KFPVPViewPiPei",				-- 跨服3v3匹配
	KFPVPPrepareView = "KFPVPPrepareView",			-- 跨服3v3准备面板
	BiaoBaiQiang = "BiaoBaiQiang",					-- 表白墙面板
	BiaoBaiRank = "BiaoBaiRank",					-- 表白排行榜
	GoPawnView = "GoPawnView",						-- 幻境寻宝
	YunbiaoView = "YunbiaoView",					-- 护送面板
	KuaFuXiuLuoTowerView = "KuaFuXiuLuoTowerView",	-- 跨服修罗塔
	FuXiuLuoTowerBuffView = "FuXiuLuoTowerBuffView",-- 跨服修罗塔buff界面
	SkyMoneyView = "SkyMoneyView",					-- 天降财宝面板
	SkyMoneyFBInfoView = "SkyMoneyFBInfoView",		-- 天将财宝副本信息面板
	Flowers = "Flowers",							-- 送花界面
	BackFlowers = "BackFlowers",					-- 被送花界面
	SkyMoneyRewardView = "SkyMoneyRewardView",		-- 天降财宝结算面板
	KaifuActivityView = "KaifuActivityView",		-- 开服活动面板
	HefuActivityView = "HefuActivityView",			-- 合服活动面板
	VersionsActivityView = "VersionsActivityView",	-- 版本活动面板
	FestivalView = "FestivalView",  				-- 版本活动面板
	CrazyHappyView = "CrazyHappyView",				-- 狂欢活动面板
	TouziActivityView = "TouziActivityView",		-- 投资活动面板
	LeiJiRechargeView = "LeiJiRechargeView",		-- 累积充值面板
	RechargeRank = "RechargeRank",					-- 充值排行面板
	ConsumeRank = "ConsumeRank",					-- 消费排行面板
	JuHuaSuan = "JuHuaSuan",						-- 聚划算
	FastCharging = "FastCharging",					-- 急速充战
	BlackMarket = "BlackMarketView", 				-- 黑市拍卖
	ThreePiece = "ThreePiece",						-- 吉祥三宝
	TreasureBowlView = "TreasureBowlView",			-- 聚宝盘
	LoginGift7View = "LoginGift7View",				-- 登录7天送礼
	TipsSpeakerView = "TipsSpeakerView",			-- 喇叭
	DailyChargeView = "DailyChargeView",			-- 每日首充
	RebateView = "RebateView",						-- 百倍返利
	TombExploreView = "TombExploreView",			-- 皇陵探险
	LimitedFeedbackView = "LimitedFeedbackView",	-- 限时大回馈
	TimeLimitGiftView = "TimeLimitGiftView",		--限时礼包界面
	GiftLimitBuy = "GiftLimitBuy",					--限购礼包
	TombExploreFBView = "TombExploreFBView",		-- 皇陵探险副本信息
	ClashTerritory = "ClashTerritory",				-- 领土战
	ClashTerritoryInfo = "ClashTerritoryInfo",		-- 领土战信息面板
	ClashTerritoryShop = "ClashTerritoryShop",		-- 领土战商店面板
	ElementBattleFightView = "ElementBattleFightView",		-- 元素战场信息面板
	DabaoBossInfoView = "DabaoBossInfoView",		-- 打宝秘境信息面板
	ActiveBossInfoView = "ActiveBossInfoView",		-- 活跃秘境信息面板
	BossFamilyInfoView = "BossFamilyInfoView",		-- boss之家信息面板
	BossFamilyFightViewTwo = "BossFamilyFightViewTwo",	-- boss之家信息面板2
	SecretBossFightView = "SecretBossFightView",    -- 密藏boss信息面板
	BabyBossFightView = "BabyBossFightView",		-- 宝宝boss信息面板
	ShangguBossFightView = "ShangguBossFightView",	-- 上古BOSS信息面板
	CrossBossFightView = "CrossBossFightView",		-- 跨服BOSS信息面板
	TipsFocusBossEncounterView = "TipsFocusBossEncounterView",	-- 仙宠奇遇boss提醒弹框
	CityCombatView = "CityCombatView",				-- 攻城战
	CityCombatFirstView = "CityCombatFirstView",	-- 第一次开攻城战
	ThreeOtherFirstView = "ThreeOtherFirstView",	-- 第一次开三界争锋
	BeherrscherShowView = "BeherrscherShowView", 	-- 三界霸主展示面板
	LianFuDuoChengFirstView = "LianFuDuoChengFirstView",	-- 第一次开连城夺城
	GuildFirstView = "GuildFirstView",				-- 第一次工会争霸
	CityCombatFBView = "CityCombatFBView",			-- 攻城战副本信息
	CityReward = "CityReward",						-- 攻城战副本信息
	HeFuCombatFirstView = "HeFuCombatFirstView",	-- 合服攻城战面板
	XianMengWarView = "XianMengWarView",			-- 合服仙盟争霸面板
	GuildShowView = "GuildShowView", 				-- 仙盟输出展示面板
	WorshipView = "WorshipView",					-- 膜拜面板
	CrossCrystalInfoView = "CrossCrystalInfoView",	-- 跨服水晶信息面板
	GuildYunBiao = "GuildYunBiao",					-- 仙盟运镖
	GuildYunBiaoTips = "GuildYunBiaoTips",			-- 仙盟运镖提示界面
	GuildWarehouseView = "GuildWarehouseView",		-- 仙盟仓库面板
	DropDownFixationView = "DropDownFixationView",	-- 固定的下拉列表
	DropDownScrollView = "DropDownScrollView",		-- 可滚动的下拉列表
	FirstChargeView = "FirstChargeView",			-- 首充
	SecondChargeView = "SecondChargeView",			-- 二充
	LeiJiDailyView = "LeiJiDailyView",				-- 每日累充
	DailyTaskFb = "DailyTaskFb",					-- 日常任务副本
	OpenFirstcharge = "open_firstcharge",			-- 首次打开首充
	FbIconView = "FbIconView",						-- 副本图标界面
	QuickSell = "QuickSell",						-- 快速出售
	Mojie = "Mojie",								-- 魔戒
	MojieMainView = "MojieMainView",				-- 魔戒主界面
	MojieGift = "MojieGift",						-- 魔戒礼包
	ModelGift = "ModelGift",						-- 模型礼包	
	MoLong = "MoLong",								-- 魔龙
	Symbol = "Symbol",								-- 符灵
	AncientRelics = "AncientRelics",				-- 上古遗迹
	PuzzleView = "PuzzleView",						-- 寻字豪礼
	LoadingTips = "LoadingTips",					-- 加载提示
	MagicWeaponView = "MagicWeaponView",			-- 魔器面板
	PetView = "PetView",							-- 宠物
	Reincarnation = "Reincarnation",				-- 转生
	ConsumeDiscountView = "ConsumeDiscountView",	-- 连消特惠
	DailyRebateView = "DailyRebateView",			-- 天天返利
	BuyOneGetOneView = "BuyOneGetOneView",			-- 买一送一
	ConsunmForGiftView = "ConsunmForGiftView", 		-- 消费有礼.
	HpBag = "HpBag",								-- 血包
	SpiritFazhenHuanHuaView = "SpiritFazhenHuanHuaView", --精灵法阵幻化
	SpiritHaloHuanHuaView = "SpiritHaloHuanHuaView", --精灵光环幻化
	FunOpenVictoryView = "FunOpenVictoryView",		-- 功能开启副本胜利面板
	MountFuBenView = "MountFuBenView",				-- 功能开启坐骑面板
--	WingFuBenView = "WingFuBenView",				-- 功能开启羽翼面板
	JingLingFuBenView = "JingLingFuBenView",		-- 功能开启精灵面板
	TipsRenameView = "TipsRenameView",				-- 改名面板
	TimeLimitBigGiftView = "TimeLimitBigGiftView",  -- 限时豪礼
	XianShiLianChongView = "XianShiLianChongView",	-- 限时连充
	ResetDoubleChongzhiView = "ResetDoubleChongzhiView",	--普天同庆
	GuildBoss = "GuildBossView",					-- 公会BOSS
	GuildApply = "GuildApplyView",					-- 公会招人面板
	GuildBoxGetTips = "GuildBoxGetTips",			-- 仙盟铸剑领取tips
	BuffPandectTips = "BuffPandectTips",			-- buff总览
	ChatGuild = "ChatGuild",						-- 公会聊天面板
	MolongMibaoView = "MolongMibaoView",			-- 魔龙秘宝(现叫极限挑战)
	TianShuView = "TianShuView",					-- 天书寻主
	TipsGuildTransfer = "TipsGuildTransfer",		-- 公会成员职位任命面板
	PlayerTitleHuanhua = "PlayerTitleHuanhua",		-- 角色称号进阶（幻化）面板
	WelcomeView = "WelcomeView",					-- 新手欢迎面板
	TempMount = "tempmount",						-- 临时坐骑
	TempWing = "tempwing",							-- 临时形象
	TipShop = "TipShop",							-- 商城购买Tip
	FBWingStoryView = "FBWingStoryFb",				-- 羽翼剧情副本
	StoryView = "StoryView",						-- 剧情
	StoryEntranceView = "StoryEntranceView",		-- 剧情入口面板
	LineView = "LineView",							-- 分线面板
	ExchangeTip = "ExchangeTip",					-- 兑换Tip
	TipsDoubleHitView = "TipsDoubleHitView",		-- 连击面板
	MarryMe = "MarryMe",							-- 我们结婚吧
	PerfectLover = "PerfectLover",					-- 完美情人
	ActiviteHongBao = "ActiviteHongBao",			-- 开服红包
	ExpRefine = "ExpRefine",						-- 经验炼制
	DisCount = "DisCount",							-- 特惠豪礼
	GoldMemberView = "gold_member",					-- 黄金会员
	GoldMemberShop = "gold_member_shop",			-- 黄金会员商店
	QuanMinChongBangView = "QuanMinChongBangView",	-- 比拼活动
	MainUIIconList = "MainUIIconList",				-- 精彩活动选择列表
	MainUIGoddessSkillTip = "MainUIGoddessSkillTip",-- 主界面女神技能提示面板
	TreasureRewardShow = "TreasureRewardShow",		-- 寻宝展示
	PersonalGoals = "PersonalGoals",				-- 个人目标
	PersonalTips = "PersonalTips",					-- 个人挂机tips
	CollectGoals = "CollectGoals",					-- 集体目标
	Rune = "Rune",									-- 符文系统
	RuneBag = "RuneBag",							-- 符文背包
	RuneAwakenView = "RuneAwakenView", 				-- 符文觉醒
	RuneAwakenTipsView = "RuneAwakenTipsView",		-- 符文觉醒tips
	RuneItemTips = "RuneItemTips",					-- 符文tips
	RuneTowerView = "RuneTowerView",				-- 符文塔
	RuneTowerFbInfoView = "RuneTowerFbInfoView",	-- 符文塔副本信息
	RuneTowerOfflineInfoView = "RuneTowerOfflineInfoView", -- 符文塔离线挂机信息面板
	RunePreview = "RunePreview", 					-- 符文总览面板
	SceneLoading = "SceneLoading",					-- 场景加载
	RandSystem = "RandSystem",						-- 随机系统公告
	ShenGeView = "ShenGeView",						-- 神格面板
	ShenGeComposeView = "ShenGeComposeView",		-- 神格合成
	ShenGeSelectView = "ShenGeSelectView",			-- 神格选择
	ShenGeOperateView = "ShenGeOperateView",		-- 神格操作面板
	ShenGeItemTips = "ShenGeItemTips",				-- 神格tips
	ShenGeAttrView = "ShenGeAttrView",				-- 神格属性预览面板
	ShenGePreview = "ShenGePreview", 				-- 神格总览面板
	ShenGeUpgradeView = "ShenGeUpgradeView",		-- 神格升级面板
	ShenGeFenJie = "ShenGeFenJie",					-- 神格分解
	ShenGeDecomposeView = "ShenGeDecomposeView",			-- 神格分解面板
	ShenGeDecomposeDetailView = "ShenGeDecomposeDetailView",		-- 神格分解详情面板
	WaBao = "WaBao",									-- 挖宝
	ShenGePropTipView = "ShenGePropTipView",			-- 神格祈福道具预览
	HunQiSkillTips = "HunQiSkillTips",				-- 魂器技能描述界面
	ShengXiaoSkillView = "ShengXiaoSkillView",		-- 生肖技能

	MiJiComposeView = "MiJiComposeView",			-- 星座秘籍合成   （暂用）
	MiJiSelectView = "MiJiSelectView",				-- 星座秘籍选择界面
	ShenYuBossView = "ShenYuBossView",				-- 神域Boss界面
	CrossMiZangBossInfoView = "CrossMiZangBossInfoView",		-- 跨服秘藏Boss场景界面
	CrossYouMingBossInfoView = "CrossYouMingBossInfoView",		-- 跨服幽冥Boss场景界面
	BossGodMagicFightView = "BossGodMagicFightView",		-- 神魔Boss场景界面

	DaMoExChangeTips = "DaMoExChangeTips",			-- 打磨经验兑换tips
	ShengXiaoBagView = "ShengXiaoBagView",			-- 生肖背包
	ShengXiaoMijiView = "ShengXiaoMijiView",		-- 生肖秘籍
	ShengXiaoSuitView = "ShengXiaoSuitView",		-- 生肖套装
	ShengXiaoEquipBag = "ShengXiaoEquipBag",		-- 生肖装备二级框
	ShengXiaoResolveView = "ShengXiaoResolveView",	-- 生肖分解
	MijiBagView = "MijiBagView",					-- 秘籍背包
	HunQiView = "HunQiView",						-- 魂器面板
	HunYinSuitView = "HunYinSuitView",				-- 魂印套装面板
	HunYinResolve = "HunYinResolve",				-- 魂印分解
	HunYinExchangView = "HunYinExchangView",		-- 魂印兑换
	HunYinAllView = "HunYinAllView",				-- 魂印总览面板
	HunYinReplaceTipsView = "HunYinReplaceTipsView",-- 魂印替换tips
	HunYinInlayTips = "HunYinInlayTips",			-- 魂印镶嵌tips
	HunQiXiLianStuffView = "HunQiXiLianStuffView",	-- 魂印洗练材料界面
	HunQiBaoExchangView = "HunQiBaoExchangView",
	GatherSoulView = "GatherSoulView",				-- 聚魂面板
	FreeGiftView = "FreeGiftView",					-- 0元礼包活动
	ShengXiaoView = "ShengXiaoView",				-- 生肖面板
	AdvanceEquipView = "AdvanceEquipView",			-- 进阶装备
	AppearacneEquipView = "AppearacneEquipView",	-- 外观装备
	TipsCommonExplainView = "TipsCommonExplainView",-- 提示说明面板
	PreferredSizeAttrView = "PreferredSizeAttrView",-- 自适应属性总览面板
	AdvanceEquipSkillView = "AdvanceEquipSkillView",-- 进阶装备技能面板

	XingXiangView = "XingXiangView",				-- 星象
	XingXiangInfoView = "XingXiangInfoView",		-- 星象
	XingXiangRecycle = "XingXiangRecycle",			-- 星象分解
	YewaiGuajiView = "YewaiGuajiView",
	SpiritExploreView = "SpiritExploreView", 		-- 精灵家园
	SpiritBagView = "SpiritBagView",				-- 精灵背包
	SpiritExpRewardView = "SpiritExpRewardView", 	-- 精灵探险开箱界面
	SpiritExpFightView = "SpiritExpFightView", 		-- 精灵探险战斗界面
	SpiritChooseModelView = "SpiritChooseModelView",-- 精灵探险选择难度界面
	SpiritHomeFightView = "SpiritHomeFightView",	-- 精灵家园战斗界面
	SpiritHomeRevengeView = "SpiritHomeRevengeView",-- 精灵家园复仇界面
	SpiritExploreVictory = "SpiritExploreVictory",  -- 精灵探险胜利界面
	SpiritExploreLose = "SpiritExploreLose", 		-- 精灵探险失败界面
	SoulHandBook = "SoulHandBookView",  			-- 精灵图鉴
	SoulQuickFlushView="SoulQuickFlushView",		-- 精灵自动改命界面
	YiZhanDaoDiView = "YiZhanDaoDiView",  			-- 一战到底
	YiZhanFinishRewardView = "YiZhanFinishRewardView",  			-- 一战到底
	ShenShou = "ShenShou",  						-- 神兽
	ShenShouBag = "ShenShouBag",  					-- 神兽背包
	ShenShouSelectEquip = "ShenShouSelectEquip",	-- 神兽装备
	FulingSelectMaterialView = "FulingSelectMaterialView",	-- 神兽装备强化材料选择界面
	FulingTips = "FulingTips",						-- 神兽装备强化提示框
	ShengQiEquipSpirit = "ShengQiEquipSpirit",		-- 圣器附灵
	ShengQiEquipStrength = "ShengQiEquipStrength",	-- 圣器强化
	ShengQiKillView = "ShengQiKillView",			-- 圣器分解
	YuLeView="YuLeView",  							-- 娱乐
	FishPondListView="FishPondListView",  			-- 鱼池玩家列表界面
	YangFishView="YangFishView",  					-- 养鱼界面
	BeStealRecordView="BeStealRecordView",  		-- 鱼被偷记录
	HarvestRecordView="HarvestRecordView",  		-- 收获记录
	WorldQuestionView = "WorldQuestionView",		-- 世界答题
	GoldHuntView = "GoldHuntView", 					-- 黄金猎场
	GroupPurchaseView = "GroupPurchaseView",		--组合购买
	QuickFlushView = "QuickFlushView",				-- 快速刷新面板
	ActivityHall = "ActivityHall",					-- 活动卷轴
	RollingBarrageView = "RollingBarrageView",		-- 滚动弹幕界面
	KillRoleView = "KillRoleView",					-- 斩杀人物面板
	TimeLimitSaleView = "TimeLimitSaleView",		-- 限时拍卖
	LuckyChessView = "LuckyChessView",				-- 幸运棋
	HuaShen = "HuaShenView",						-- 化神
	ExpBall = "ExpBall",							-- 经验球
	KuaFuBattle = "KuaFuBattle",					-- 跨服六界
	KuaFuLiuJiePre = "KuaFuLiuJiePre",				-- 跨服六界预告
	KuaFuFightView = "KuaFuFightView",				-- 跨服六界争霸
	KuafuTaskView = "KuafuTaskView",				-- 跨服六界争霸任务
	KuaFuRecordView = "KuaFuRecordView",			-- 跨服六界争霸记录
	LuckyLogView = "LuckyLogView",					--通用日志
	DailyTaskView = "DailyTaskView",
	PersonFullServerSnapView = "PersonFullServerSnapView", 	-- 合服活动--个人抢购
	HeFuFullServerSnapView = "HeFuFullServerSnapView", 	-- 合服活动--全服抢购
	CombineServerBossView = "CombineServerBossView",	-- 合服boss
	SecretrShopView = "SecretrShopView",				-- 臻品城/神秘商店
	TotemView = "TotemView",                        -- 图腾
	ShenYinView = "ShenYinView",                        -- 神印
	Shenqi = "Shenqi", 								-- 神器
	ShenYinYinJiTipView = "ShenYinYinJiTipView",    -- 神印印记
	ShenYinYinJiExchangeView = "ShenYinYinJiExchangeView", -- 神印印记兑换
	KuaFuTuanZhanTaskView = "KuaFuTuanZhanTaskView",-- 跨服团战任务界面
	KuaFuTuanZhanRankView = "KuaFuTuanZhanRankView",-- 跨服团战排行榜界面
	KuaFuTuanZhanRewardView = "KuaFuTuanZhanRewardView",--跨服团战排行奖励界面
	PackageView = "PackageView",					--背包界面
	ShengYinEquip = "ShengYinEquip",				--圣印装备
	KFMonthBlackWindHigh = "KFMonthBlackWindHigh",			--跨服月黑风高(珍宝秘境)
	LuanDouBattleView = "LuanDouBattleView",		--乱斗战场面板
	LuanDouRewardView = "LuanDouRewardView",		--乱斗战场每轮面板
	LuanDouFinishRewardView = "LuanDouFinishRewardView",		--乱斗战场结束面板
	LuanDouBattleRewardView = "LuanDouBattleRewardView",		--乱斗战场奖励查看
	FishingView = "FishingView",					-- 跨服钓鱼
	TipsFishingSuccView = "TipsFishingSuccView",			-- 钓鱼成功界面
	ActiveBossRankRewardView = "ActiveBossRankRewardView",	-- 活跃BOSS伤害排行奖励
	BaoBaoLongFengTipsView = "BaoBaoLongFengTipsView",		-- 龙凤宝宝界面
	ShenQiEffectTips = "ShenQiEffectTips",					-- 奇兵遁甲特效激活界面
	OneYuanSnatchView = "OneYuanSnatchView",				-- 一元夺宝
	KuaFuTargetView = "KuaFuTargetView",					-- 跨服目标
	SmallHelper = "SmallHelper",							-- 小助手

	-- 提示框
	TipsPropView = "TipsPropView",					-- 道具提示TIP
	TipsEquipView = "TipsEquipView",				-- 装备TIP
	TipsMojieView = "TipsMojieView",				-- 魔戒装备TIP
	TipsOtherEquipView = "TipsOtherEquipView",		-- 其他装备TIP
	TipsShowProView = "TipsShowProView",			-- 聊天背包TIP
	TipsZhiBaoSkillView = "TipsZhiBaoSkillView",	-- 功勋技能TIP
	TipsItemGetWayView = "TipsItemGetWayView",		-- 道具不足物品提示TIP
	TipsExpressView = "TipsExpressView",			-- 表情TIP
	TipsPortraitView = "TipsPortraitView",			-- 更换头像TIP
	TipsOtherPortraitView = "TipsOtherPortraitView",-- 查看头像TIP
	TipsCommonBuyView = "TipsCommonBuyView",		-- 快速购买TIP
	TipsCommonAutoView = "TipsCommonAutoView",		-- 自动购买TIP
	TipsInviteView = "TipsInviteView",				-- 邀请TIP
	TipsAddFriendView = "TipsAddFriendView",		-- 添加好友TIP
	TipsCommonInputView = "TipsCommonInputView",	-- 数字输入TIP
	TipExchangeView = "TipExchangeView",			-- 兑换TIP
	TipsRewardView = "TipsRewardView",				-- 奖励TIP
	TipsStarRewardView = "TipsStarRewardView",				-- 奖励TIP2
	TipsGiftsRewardView = "TipsGiftsRewardView",	-- 开启礼包TIP
	TipsGetNewitemView = "TipsGetNewitemView",		-- 获得新物品TIP
	TipsLackDiamondView = "TipsLackDiamondView",	-- 钻石不足TIP
	TipsLockVipView = "TipsLockVipView",			-- Vip不足TIP
	TipsLackJiFenView = "TipsLackJiFenView",		-- 积分不足TIP(金猪召唤/龙神夺宝)
	ShenYinSuitAttrView = "ShenYinSuitAttrView",			--圣印套装TIP
	GuajiMapTips = "GuajiMapTips",					-- 挂机地图提示
	TipsTreasureWarehouseView = "TipsTreasureWarehouseView",	-- 寻宝仓库（独立）
	TipsCommonTwoOptionView = "TipsCommonTwoOptionView",	--
	TipsCommonOneOptionView = "TipsCommonOneOptionView",	--
	TipsCommonPlaneTipsView = "TipsCommonPlaneTipsView",	--
	TipsHelpView = "TipsHelpView",		--
	TipsAttrView = "TipsAttrView",		--
	TipsAttrAllView = "TipsAttrAllView",		--
	TipsTotalAttrView = "TipsTotalAttrView",		--
	HappyTreeExchangeView = "HappyTreeExchangeView",		--
	TipsSpiritEquipView = "TipsSpiritEquipView",		--
	TipsSpiritShangZhenView = "TipsSpiritShangZhenView",	--
	TipsSpiritZhenFaValueView = "TipsSpiritZhenFaValueView", --
	TipsSpiritZhenFaPromoteView = "TipsSpiritZhenFaPromoteView", --
	TipOpenFunctionView = "TipOpenFunctionView",		--
	TipsChosenFlowerView = "TipsChosenFlowerView",		--
	TipsMissionCompletedView = "TipsMissionCompletedView",		--
	TisDailySelectItemView = "TisDailySelectItemView",		--
	TipsSpiritSoulView = "TipsSpiritSoulView",		--
	TipsSpiritDressSoulView = "TipsSpiritDressSoulView",		--
	TipsShortCutEquipView = "TipsShortCutEquipView",		--
	TipsGetEquipView = "TipsGetEquipView",		--
	TipsDisplayPropModleView = "TipsDisplayPropModleView",		--
	TipsEquipCompareView = "TipsEquipCompareView",		--
	TipsOtherRoleEquipView = "TipsOtherRoleEquipView",		--
	TipsWorldLevelView = "TipsWorldLevelView",
	TipsPlayerAttrView = "TipsPlayerAttrView",
	TipOpenFunctionFlyView = "TipOpenFunctionFlyView",		--
	TipsAchievementView = "TipsAchievementView",		--
	TipsOtherHelpView = "TipsOtherHelpView",		--
	TipSkillView = "TipSkillView",		--
	TipSpecialSkillView = "TipSpecialSkillView",
	TipsQuickUsePropView = "TipsQuickUsePropView",		--
	TipsReminding = "TipsReminding",		--
	TipsBossInfoView = "TipsBossInfoView",		--
	TipsOtherEquipCompareView = "TipsOtherEquipCompareView",		--
	TipsStandbyMaskView = "TipsStandbyMaskView",		--
	TipsActivityRewardView = "TipsActivityRewardView",		--
	TipsOpenTrailerView = "TipsOpenTrailerView",		--
	TipsDayOpenTrailerView = "TipsDayOpenTrailerView",
	TipsKillBossView = "TipsKillBossView",
	TipsFuBenShowView = "TipsFuBenShowView",		--
	TipsFocusBossView = "TipsFocusBossView",		--
	TipsBossFocusView = "TipsBossFocusView",
	TipsFirstChargeView = "TipsFirstChargeView",		--
	TipJueXingView = "TipJueXingView",		--
	TipsExpFuBenView = "TipsExpFuBenView",			--
	TipsExpInSprieFuBenView = "TipsExpInSprieFuBenView",		--
	TipsExpFuBenGuWuView = "TipsExpFuBenGuWuView",
	PreRewardView = "PreRewardView",  		   				--
	TipNewSystemNoticeView = "TipNewSystemNoticeView",		--
	CheckEquipView = "CheckEquipView",
	TipsGongGaoView = "TipsGongGaoView",					--公告
	TipsDisconnectedView = "TipsDisconnectedView", 			--断线重连
	TipWarmView = "TipWarmView", -- 温馨提示
	TipPaTaView = "TipPaTaView", -- 爬塔
	TipPaTaRewardView = "TipPaTaRewardView", -- 爬塔
	FuBenFinishStarNextView = "FuBenFinishStarNextView", -- 爬塔
	TipGuildRewardView = "TipGuildRewardViFew", 			-- 公会宝箱奖励
	TipsEnterFbView = "TipsEnterFbView", 	   				-- 进入副本
	TipsShowSkillView = "TipsShowSkillView",  				--技能tips2
	TipWaBaoView = "TipWaBaoView",  		   				--挖宝tips
	BossSkillWarning = "BossSkillWarning",  		  		--boss技能警告
	ErnieView = "ErnieView",  		   						--摇奖机
	JuBaoPen = "JuBaoPen",  		   						--聚宝盆
	SpiritSkillQuickFlushView = "SpiritSkillQuickFlushView",--技能快速刷新
	TipsSpiritAptitudeView="TipsSpiritAptitudeView",
	TipsSpiritInviteView = "TipsSpiritInviteView", 			--精灵探险PK邀请框
	TipsSpiritHomeSendView = "TipsSpiritHomeSendView", 		--精灵家园选择精灵框
	TipsSpiritHomeHarvestView = "TipsSpiritHomeHarvestView",--精灵家园收获框
	TipsSpiritHomePreviewView = "TipsSpiritHomePreviewView",--精灵家园收获预览
	TipsSpiritHomeConfirmView = "TipsSpiritHomeConfirmView",--精灵家园掠夺确认
	TipsEneterCommonSceneView = "TipsEneterCommonSceneView",-- 进入普通场景提示
	TipsCompleteChapterView = "TipsCompleteChapterView",	-- 完成章节任务提示
	TipsSpiritExpBuyBuffView = "TipsSpiritExpBuyBuffView",  -- 精灵探险购买BUFF
	TipsGoToRelicView = "TipsGoToRelicView",				--前往遗迹采集的窗口
	TipsUseLuckyItemView = "TipsUseLuckyItemView",			--基础装升级使用幸运符的窗口
	TipsTaskRewardRollView = "TipsTaskRewardRollView",		--任务转盘
	TipsGuildWarSmallView = "TipsGuildWarSmallView",		--仙盟盟战奖励
	TipKfLiujieReward = "TipKfLiujieReward",				--跨服六界奖励
	TipJiTiReward = "TipJiTiReward",						--集体奖励
	TipLuoShu = "TipLuoShu",								--洛书进阶
	ActivityEndView = "ActivityEndView",					--活动结束界面
	TimeLimitTitleView = "TimeLimitTitleView",
	GoalTimeLimitTitleView = "GoalTimeLimitTitleView",
	TipsSpecialHuanHuaView = "TipsSpecialHuanHuaView",		--幻化超强战力提示面板
	MolongMibaoTips = "MolongMibaoTips",					--嘉年华tips
	FBDropView = "FBDropView",								--副本掉落界面
	BaiZhanSuitView = "BaiZhanSuitView",					--百战套装预览

	TreasureLoftView = "TreasureLoftView",					--套装探秘
	FanFanZhuanView = "FanFanZhuanView",					--翻翻转
	RepeatRechargeView = "RepeatRechargeView",				--循环充值
	LuckWishingView = "LuckWishingView",					--幸运许愿
	SingleRechargeView = "SingleRechargeView",				--单返豪礼
	IncreaseCapabilityView = "IncreaseCapabilityView",		--冲战达人
	IncreaseSuperiorView = "IncreaseSuperiorView",			--冲战高手
	MarryNoticeView = "MarryNoticeView",					--结婚通知
	GoddessSearchAuraView="GoddessSearchAuraView",			--女神觅灵
	TipsCongratulationView = "TipsCongratulationView",		--好友贺礼
	PlantTreeView = "PlantTreeView",						--趣味植树
	LoopChargeView = "LoopChargeView",						--送装备
	ImageSkillView = "ImageSkillView",						--形象秒杀
	CrazyMoneyTreeView = "CrazyMoneyTreeView",				--疯狂摇钱树
	DoubleGoldView = "DoubleGoldView",						--双倍元宝
	HappyHitEggView = "HappyHitEggView",					--欢乐砸蛋
	Weekend_HappyView = "WeekendHappyView",					--周末狂欢
	LongXingView = "LongXingView",							--龙行天下界面
	LuckyShoppingView = "LuckyShoppingView", 				--幸运云购
	CongratulationView = "CongratulationView",
	JiFenShopView = "JiFenShopView",
	MarryBlessingView = "MarryBlessingView",				--结婚祝贺
	FriendExpBottleView = "FriendExpBottleView",			--好友经验瓶
	JinYinTaView = "JinYinTaView",				           --金银塔运营活动
	MiningView = "MiningView",								--决斗场
	MiningRecordListView = "MiningRecordListView",			--决斗场 - 记录面板
	MiningSelectedView = "MiningSelectedView",				--决斗场 - 选择矿物面板
	MiningTargetView = "MiningTargetView",					--决斗场 -
	SeaRewardView = "SeaRewardView",						--决斗场 -
	SeaSelectedView = "SeaSelectedView",					--决斗场 -
	MiningRewardView = "MiningRewardView",					--决斗场 -
	KaiFuInvestView = "KaiFuInvestView",
	KiaFuRisingStarView = "KiaFuRisingStarView",            -- 升星助战
	ZhuangZhuangLe = "ZhuangZhuangLeView",                  -- 转转乐
	FlowerReMindView = "FlowerReMindView",
	RareDial = "RareDialView",								--珍稀转盘
	ZhuanLunQucikFlushView = "ZhuanLunQucikFlushView",		--珍稀转盘快速刷新界面
	MapFindView = "MapFindView",							--地图寻宝
	RechargeCapacity = "RechargeCapacityView",				--冲战先锋
	MapFindRewardView = "MapFindRewardView",				--地图寻宝奖励
	MapfindRushView = "MapfindRushView",					--地图快速刷新
	LuckyDrawView = "LuckyDrawView",						--神隐占卜屋
	LuckyDrawAutoPopView = "LuckyDrawAutoPopView",			--神隐占卜屋快速占卜界面
	TreasureBusinessmanView = "TreasureBusinessmanView",	--至尊豪礼
	KuafuTaskRecordView = "KuafuTaskRecordView",
	KuafuLiujieRewardTip = "KuafuLiujieRewardTip",
	FarmSceneView = "FarmSceneView",						-- 农场界面
	HappyRechargeView = "HappyRechargeView",				--充值乐翻天
	HappyRecordListView = "HappyRecordListView",			--充值乐翻天记录
	HuanZhuangShopView = "HuanZhuangShopView",		   	--幻装商城
	ShenYinTianXiangAttrView = "ShenYinTianXiangAttrView",		   	--天象总属性
	ShenYinTianXiangChangeView = "ShenYinTianXiangChangeView",		--天象换珠界面
	RechargeReturnReward = "RechargeReturnReward",			-- 疯狂返利（狂返元宝）
	TianXiangGroupAttrView = "TianXiangGroupAttrView",		--天象换珠界面
	ShenYinQiangHuaAttrView = "ShenYinQiangHuaAttrView",		--强化属性界面
	CornucopiaView = "CornucopiaView",
	RoleShenEquipView = "RoleShenEquipView",					-- 大天使界面 
	ImmortalView = "ImmortalView",								-- 仙尊卡
	OneYuanBuyView = "OneYuanBuyView",							-- 0元购
	ImmortalTipsView = "ImmortalTipsView",						-- 仙尊卡永久激活面板
	TipsRecordView = "TipsRecordView",							-- 跨服修罗塔掉落日志
	TipsWelareFindView = "TipsWelareFindView",					-- 福利找回tips
	TipsLiuJieLogView = "TipsLiuJieLogView",					-- 跨服六界掉落日志
	CreelPanel = "CreelPanel", 									-- 跨服钓鱼兑换面板
	LuanDouBattleAllRewardView = "LuanDouBattleAllRewardView", 	-- 乱斗战场总奖励预览
	LittlePetHomeRecycleView = "LittlePetHomeRecycleView" ,     -- 小宠物回收
	LittlePetHomePackageView = "LittlePetHomePackageView",		-- 小宠物背包
	LittlePetHandleBookView = "LittlePetHandleBookView",		-- 小宠物图鉴
	LittlePetWarehouseView = "LittlePetWarehouseView",			-- 小宠物仓库
	LittlPetPropTipView = "LittlPetPropTipView",				-- 小宠物商店提示框
	LittlePetToyBagView = "LittlePetToyBagView",				-- 小宠物玩具背包
	LittlePetRecycleSelectView = "LittlePetRecycleSelectView",	-- 小宠物回收筛选面板
	ClothespressView = "ClothespressView",						-- 衣橱
	SuitAttrTipView = "SuitAttrTipView",						-- 衣橱套装属性面板
	SuitModelTipView = "SuitModelTipView",						-- 衣橱套装模型面板
	KuaFuTuanZhanRoundRewardView = "KuaFuTuanZhanRoundRewardView",-- 跨服每轮奖励信息
	SanShengProgView = "SanShengProgView",						-- 三生三世进度面板
	LingKunBattleDetailView = "LingKunBattleDetailView",		-- 灵鲲之战面板
	LingKunBattleSceneView = "LingKunBattleSceneView",			-- 灵鲲之战场景面板
	LingKunBattleBossView = "LingKunBattleBossView",			-- 灵鲲之战Boss预览
	AdvancedAct = "advanced_act",								-- 进阶活动
	ConsumeRewardView = "ConsumeRewardView",					-- 消费返礼
	SecretTreasureHuntingView = "SecretTreasureHuntingView",	-- 秘境寻宝
	CompetitionActivity = "CompetitionActivity",
	SingleRebateView = "SingleRebateView", 						--单笔返利
	AdvancedReturn = "AdvancedReturn",							-- 进阶返还
	AdvancedReturnTwo = "AdvancedReturnTwo",					-- 进阶返还2
	BiPingActivity = "BiPingActivity",							-- 比拼活动
	HappyErnieView = "HappyErnieView",							-- 欢乐摇奖
	TitleShopView = "TitleShopView",							-- 你充我送	
	SinglePartyInfoView = "SinglePartyInfoView",    			-- 吃鸡盛宴
	EuropeanWeddingView = "EuropeanWeddingView", 				-- 西式婚礼面板
	MarriageHaloBuyView = "MarriageHaloBuyView", 				-- 光环特购面板
	WeddingTipsOne = "WeddingTipsOne",							-- 温馨婚礼提示面板
	WeddingTipsTwo = "WeddingTipsTwo",							-- 喜庆婚礼提示面板
	WeddingTipsThree = "WeddingTipsThree",						-- 豪华婚礼提示面板
	CoupleHomeView = "CoupleHomeView",							-- 夫妻家园
	CoupleHomePreView = "CoupleHomePreView",					-- 夫妻家园预览
	CoupleHomeThemeBuyView = "CoupleHomeThemeBuyView",			-- 夫妻家园主题购买
	CoupleHomePacketView = "CoupleHomePacketView",				-- 夫妻家园储物箱
	CoupleHomeTotalAttrView = "CoupleHomeTotalAttrView",		-- 夫妻家园总属性
	DropView = "DropView",										-- 掉落日志
	GuildAnswerTask = "GuildAnswerTask", 						-- 仙盟晚宴
	BuyExpView = "BuyExpView",									-- 经验炼制
	KuafuGuildCollectTaxesView = "KuafuGuildCollectTaxesView",	-- 六界税收界面
	SuitCollection = "SuitCollection", 							-- 套装收集
	SuitCollecBag = "SuitCollecBag", 							-- 套装收集背包
	HunyuUpgradeShowTips = "HunyuUpgradeShowTips",				-- 魂玉升级展示面板
	MarryGiftView = "MarryGiftView",							-- 情意绵绵
	JinJieShowGoalView = "JinJieShowGoalView",					-- 进阶目的展示提示
	TipsZhanChang =  "TipsZhanChang", 							-- 战场播报
	TodayThemeView =  "TodayThemeView", 						-- 今日主题
	OffSheetSpeakView = "OffSheetSpeakView",					-- 脱单排行
	FourGradeEquip =  "FourGradeEquip", 						-- 四阶神装
	ChristmaGiftView = "ChristmaGiftView",						-- 礼物收割
	ChristmaGiftFuBenView = "ChristmaGiftFuBenView",			-- 礼物收割场景UI
	SkillGiftFuBenView = "SkillGiftFuBenView",					-- 礼物收割场景UI
	KuaFuBorderland = "KuaFuBorderland",						-- 跨服边境
	EquimentSuitView = "EquimentSuitView",						-- 装备收集
	DouQiView = "DouQiView",									-- 斗气装备
	DouQiUseItemView = "DouQiUseItemView",						-- 斗气使用物品
	DouQiEquipRecovery = "DouQiEquipRecovery",					-- 斗气装备回收
	CrystalEscortView = "CrystalEscortView",					-- 跨服水晶护送
}


TabIndex = {
	role_intro = 11,					-- 人物-信息
	role_title = 12,					-- 人物-称号
	role_active_skill = 13,				-- 人物-主动技能
	role_passive_skill = 14,			-- 人物-被动技能
	role_innate_skill = 15,				-- 人物-天赋技能
	role_rebirth = 16,					-- 人物-转生
	role_reincarnation = 17,			-- 人物-真转生
	role_tulong_equip = 18,				-- 人物-屠龙装备
	role_chuanshi_equip = 19,			-- 人物-传世装备
	role_shengyin = 20,					-- 人物圣印
	role_zhuanzhi = 21,					-- 转职
	role_juexing = 22,					-- 觉醒
	role_tianshu_skill = 23,			-- 人物-天书技能

	role_shenbing = 58,					-- 神兵

	shenshou_equip = 71,				-- 神兽-装备
	shenshou_fuling = 72,				-- 神兽-附灵
	shenshou_huanling = 73,				-- 神兽-唤灵
	shenshou_compose = 74,				-- 神兽-合成
	shenshou_shengqi = 75,				-- 神兽-圣器

	symbol_intro = 81,					-- 元素之心-元素
	symbol_fuzhou = 82,					-- 元素之心-元获
	symbol_mishi = 83,					-- 元素之心-元涌
	symbol_yuanhun = 84,				-- 元素之心-元魂
	symbol_yuanzhuang = 85,				-- 元素之心-元装
	symbol_yz_get = 86,					-- 元素之心-元装获取
	symbol_upgrade = 87,				-- 元素之心-元释

	appearance_multi_mount = 91,		-- 外观-双人坐骑
	appearance_waist = 92,				-- 外观-腰饰
	appearance_toushi = 93,				-- 外观-头饰
	appearance_qilinbi = 94,			-- 外观-麒麟臂
	appearance_mask = 95,				-- 外观-面饰
	appearance_toushi_huanhua = 98,		-- 外观-头饰幻化
	appearance_mask_huanhua = 99,		-- 外观-面饰幻化
	appearance_yaoshi_huanhua = 100,	-- 外观-腰饰幻化
	appearance_qilinbi_huanhua = 101,	-- 外观-麒麟臂幻化
	appearance_lingzhu = 102,			-- 外观-灵珠
	appearance_xianbao = 103,			-- 外观-仙宝
	appearance_lingtong = 104,			-- 外观-灵童
	appearance_linggong = 105,			-- 外观-灵弓
	appearance_lingqi = 106,			-- 外观-灵骑
	appearance_weiyan = 107,			-- 外观-尾焰
	appearance_shouhuan	= 108,			-- 外观-手环
	appearance_tail	= 109,				-- 外观-尾巴
	appearance_flypet = 110,			-- 外观-飞宠
	appearance_lingzhu_huanhua = 111, 	-- 外观-灵珠幻化
	appearance_xianbao_huanhua = 112,	-- 外观-仙宝幻化
	appearance_lingchong_huanhua = 113,	-- 外观-灵童幻化
	appearance_linggong_huanhua = 114,	-- 外观-灵弓幻化
	appearance_lingqi_huanhua = 115,	-- 外观-灵骑幻化
	appearance_weiyan_huanhua = 116,	-- 外观-尾焰幻化
	appearance_shouhuan_huanhua = 117,	-- 外观-手环幻化
	appearance_tail_huanhua = 118,		-- 外观-尾巴幻化
	appearance_flypet_huanhua = 119,	-- 外观-飞宠幻化
	appearance_multimount_huanhua = 120,-- 外观-飞宠幻化

	tianshenhuti_info = 121,			--无双装备
	tianshenhuti_compose = 122,			--无双装备合成
	tianshenhuti_conversion = 123,		--无双装备转化
	tianshenhuti_box = 124,				--无双装备宝箱

	totem_xin_fa = 150,                 -- 图腾-心法
	totem_jing_jie = 151,               -- 图腾-境界
	totem_stamp = 152,                  -- 图腾-印记
	totem_chou_jiang = 153,             -- 图腾-抽奖

	society_team = 201,					-- 社交-组队
	society_friend = 202,				-- 社交-好友
	society_enemy = 203,				-- 社交-仇人
	society_mail = 204,					-- 社交-邮件
	write_mail = 205,					-- 社交-写邮件

	camp_choose = 301,					-- 军团-选择
	camp_overview = 302,				-- 军团-军团信息
	camp_statue = 303,					-- 军团-雕像
	camp_snatch_normal = 304,			-- 军团-普通夺宝
	camp_snatch_high = 305,				-- 军团-高级夺宝
	camp_equip = 306,					-- 军团-装备
	camp_rank = 307,					-- 军团-排行
	camp_equip_soul = 308,				-- 军团-魂炼
	camp_equip_monster = 309,			-- 军团-神兽

	System_setting = 401,				-- 系统-设置
	System_guaji = 402,					-- 系统-挂机
	System_reward = 403, 				-- 系统-更新奖励

	compose_stone = 501, 				-- 合成-宝石
	compose_jinjie = 502,				-- 合成-锻造
	compose_other = 503, 				-- 合成-其他
	compose_shengqi = 504,				-- 合成-圣器
	compose_shenmo = 505,				-- 合成-圣器

	equipment_shen_shengji = 601,		-- 神装-升级
	equipment_shen_liujue = 604,		-- 神装-升仙六决
	equipment_shen_jinjie = 605,		-- 神装-功法进阶
	equipment_shen_jiefeng = 606,		-- 神装-解除封印
	equipment_jinjie = 607,				-- 神装-进阶
	equipment_shenzhu = 608,			-- 神装-神铸

	chat_compre = 701,					-- 聊天-综合
	chat_world = 702,					-- 聊天-世界
	chat_team = 703,					-- 聊天-组队
	chat_guild = 704,					-- 聊天-公会
	chat_system = 705,					-- 聊天-系统
	chat_private = 706,					-- 聊天-私聊
	chat = 707,							-- 聊天
	chat_question = 708,				-- 聊天-答题

	big_face = 801,						-- 炫酷聊天-大表情
	gold_text = 802,					-- 炫酷聊天-土豪金
	special_image = 803,				-- 炫酷聊天-特殊表情
	bubble = 804,						-- 炫酷聊天-聊天框
	head = 805,							-- 炫酷聊天-头像框

	mount_huanhua = 901,				-- 坐骑-幻化
	mount_jinjie = 902,					-- 坐骑-进阶
	-- mount_flyup = 903,				-- 坐骑-飞升
	-- mount_minghun = 904,				-- 坐骑-命魂
	wing_jinjie = 905,					-- 羽翼进阶
	halo_jinjie = 906,					-- 光环进阶
	shengong_jinjie = 907,				-- 神弓进阶
	shenyi_jinjie = 908,				-- 神翼进阶
	huashen_jinjie = 909,				-- 化神升级
	huashen_protect = 910,				-- 化神守护
	fight_mount = 911,					-- 战斗坐骑
	foot_jinjie = 912,					-- 足迹进阶
	cloak_jinjie = 913,					-- 披风进阶
	fashion_jinjie = 914,				-- 时装进阶
	immortals_jinjie = 915,				-- 神兵进阶
	fabao_jinjie = 916,					-- 法宝进阶

	wing_huanhua = 918,					-- 羽翼-幻化
	halo_huanhua = 919,					-- 光环-幻化
	fightmount_huanhua = 920,			-- 战斗坐骑-幻化
	foot_huanhua = 921,					-- 足迹-幻化
	fashion_huanhua = 922,				-- 时装-幻化
	immortals_huanhua = 923,			-- 神兵-幻化
	fabao_huanhua = 924,				-- 法宝-幻化



	img_fuling_content = 1001,			-- 形象赋灵
	img_fuling_talent_view = 1002,		-- 形象天赋
	img_fuling_talent = 1003,			-- 形象天赋
	img_fuling_suxing = 1004,			-- 形象苏醒
	-- advance_equipup_mount = 1001,	-- 进阶-装备升级-坐骑装备升级
	-- advance_equipup_wing = 1002,		-- 进阶-装备升级-羽翼装备升级
	-- advance_equipup_halo = 1003,		-- 进阶-装备升级-光环装备升级
	-- advance_equipup_shengong = 1004,	-- 进阶-装备升级-神弓装备升级
	-- advance_equipup_shenyi = 1005,	-- 进阶-装备升级-神翼装备升级

	fb_push = 1101,				 		-- 推图副本1
	fb_push_special = 1102,				-- 推图副本2
	fb_phase = 1103,					-- 阶段副本
	fb_exp = 1104,						-- 经验副本
	fb_story = 1105,					-- 剧情副本
	fb_vip = 1106,						-- VIP副本
	fb_many_people = 1108,				-- 多人副本
	-- fb_guard = 1110,					-- 品质副本（守护）
	fb_defense = 1113,					-- 塔防副本（G21）
	fb_team_tower = 1114,				-- 组队守护

	--高战副本
	fb_weapon = 1112,					-- 武器材料副本
	fb_armor = 1111,					-- 防具材料副本
	fb_quality = 1109,					-- 品质副本
	fb_guard = 1110,					-- 品质副本
	fb_tower = 1107,					-- 爬塔副本

	baoju_zhibao_active = 1200,			-- 宝具至宝活跃
	baoju_zhibao_upgrade = 1201,		-- 宝具至宝升级
	baoju_medal = 1202,					-- 宝具勋章
	baoju_achieve_title = 1203,			-- 宝具成就头衔
	baoju_achieve_overview = 1204,		-- 宝具成就总览
	baoju_jingjie = 1205,				-- 宝具境界
	baoju_luoshu = 1206,				-- 宝具洛书
	baoju_luoshu_upgrade = 1207,		-- 宝具洛书升星
	baoju_luoshu_shenhua = 1208,		-- 宝具洛书神化

	spirit_spirit = 1300,				-- 精灵的子精灵面板
	spirit_hunt = 1301,					-- 精灵猎取
	spirit_exchange = 1302,				-- 精灵兑换
	spirit_warehouse = 1303,			-- 精灵仓库
	spirit_soul = 1304,					-- 精灵命魂
	spirit_fazhen = 1305,				-- 精灵法阵
	spirit_halo = 1306,					-- 精灵光环
	spirit_skill = 1307,				-- 精灵技能
	spirit_zhenfa = 1308,				-- 精灵阵法
	spirit_home = 1309,					-- 精灵家园
	spirit_explore = 1310,				-- 精灵探险
	spirit_lingpo = 1311, 				-- 精灵灵魄
	spirit_meet = 1312, 				-- 精灵奇遇
	spirit_wuxing = 1313, 				-- 精灵悟性
	spirit_fengyin = 1314, 				-- 精灵封印
	spitit_huanhua = 1315,				-- 精灵幻化

	marriage_honeymoon = 1400,			-- 结婚蜜月
	marriage_lover = 1410,				-- 结婚对象
	marriage_monomer = 1411,			-- 结婚单身信息
	marriage_ring = 1420,				-- 结婚戒指
	marriage_weeding = 1430,			-- 结婚婚宴副本
	marriage_love_contract = 1440,		-- 结婚爱情契约
	marriage_love_halo = 1450,			-- 结婚光环
	marriage_fuben = 1401,				-- 结婚情缘副本
	marriage_halo = 1403,				-- 结婚互动
	marriage_halo_content = 14031,		-- 结婚光环(已废弃)
	marriage_love_tree = 14032,			-- 结婚相思树
	marriage_baobao = 1404,				-- 结婚宝宝
	marriage_biaobai = 1405,			-- 结婚表白
	marriage_baobao_bless = 1415,		-- 结婚宝宝祈福
	marriage_baobao_guard = 1426,		-- 结婚宝宝守卫
	marriage_equip = 1460,				-- 结婚装备
	marriage_equip_suit = 1461,			-- 结婚装备套装
	marriage_equip_recyle = 1462,		-- 结婚装备回收
	marriage_shengdi = 1470,			-- 情缘圣地
	marriage_honey = 1471,				-- 结婚蜜月

	marriage_baobao_att = 1480,			-- 结婚宝宝
	marriage_baobao_bless = 1481,		-- 宝宝祈福
	marriage_baobao_guard = 1482,		-- 宝宝守卫
	marriage_baobao_zizhi = 1483,		-- 宝宝资质
	
	-- 不要动这个index，有实际用途（这个index必须得是顺序递增的）
	couple_home_home = 82001,			-- 夫妻家园-布置
	couple_home_shop = 82002,			-- 夫妻家园-商城
	couple_home_buy = 82003,			-- 夫妻家园-购买房子

	guild_info = 1500,					-- 公会信息
	guild_member = 1501,				-- 公会成员
	guild_box = 1502,					-- 公会宝箱
	guild_altar = 1503,					-- 公会祭坛
	guild_totem = 1504,					-- 公会图腾
	guild_territory = 1505,				-- 公会领地
	guild_list = 1506,					-- 公会列表
	guild_activity = 1507,				-- 公会活动
	guild_storge = 1508,				-- 公会仓库
	guild_donate = 1509,				-- 公会捐献
	guild_request = 1510,				-- 公会申请
	guild_maze = 1511,					-- 公会迷宫
	guild_war = 1512,					-- 公会盟战

	activity_daily = 1601,				-- 活动-活动大厅
	activity_battle = 1602,				-- 活动-战场大厅
	activity_kuafu_battle = 1603,		-- 活动-跨服战场

	forge_advance = 1700,				-- 装备-进阶
	forge_strengthen = 1701,			-- 装备-强化
	forge_gem = 1702,					-- 装备-宝石
	forge_quality = 1710,				-- 装备-品质
	forge_yongheng = 1711,				-- 装备-永恒
	forge_cast = 1712,					-- 装备-强化 神铸
	forge_up_star = 1720,				-- 装备-升星
	forge_jade = 1721, 					-- 装备-玉石
	forge_jade_refine = 1722,			-- 装备-玉石精炼
	forge_deity_intersify = 1730,		-- 装备-附灵
	forge_deity_suit = 1731,			-- 装备-套装
	forge_extreme_suit = 1732,			-- 装备-至尊
	forge_jue_xing = 1733,				--装备-觉醒
	forge_exchange = 1734,				--装备-合成

	-- forge_cast = 103,					--装备-神铸
	-- forge_suit = 105,					--装备-套装
	-- forge_compose = 106,				--装备-合成
	-- forge_red_equip = 110,				--装备-红色装备
	-- forge_base_equip =111,              --装备-基础装
	-- forge_fly_immed =112,              --装备-飞仙

	world_boss = 2600,					-- BOSS-世界BOSS
	kf_boss = 2601,						-- BOSS-跨服BOSS
	vip_boss = 2602,					-- BOSS-VIPBOSS
	miku_boss = 2603,					-- BOSS-密窟BOSS
	dabao_boss = 2604,					-- BOSS-打宝秘境
	active_boss = 2605,					-- BOSS-活跃Boss
	-- secret_boss = 2606,              -- Boss-秘藏Boss
	personal_boss = 2607,				-- Boss-个人Boss
	baby_boss = 2608,					-- Boss-宝宝Boss
	shanggu_boss = 2609,				-- Boss-上古Boss
	tujian_boss = 2610,					-- Boss-Boss图鉴
	drop = 2611,						-- Boss-掉落日志
	shenyu_boss_tujian = 2612,			-- 神域Boss-图鉴
	shenyu_secret = 2613,				-- 神域Boss-秘藏
	shenyu_youming = 2614,				-- 神域Boss-幽冥
	shenyu_zhengbao = 2615,				-- 神域boss珍宝秘境
	nuzhan_jiuxiao = 2616,				-- 怒斩九霄
	luandou_zhanchang = 2617, 			-- 乱斗战场
	shenyu_godmagic = 2618,				-- 神域Boss-神魔

	market_buy = 1700,					-- 市场-购买界面
	market_sell = 1701,					-- 市场-出售界面
	market_table = 1702,				-- 市场-货架界面
	market_purchase = 1704,				-- 市场-收购界面

	helper_zhanli = 1800,				-- 小助手-战力评估
	helper_upgrade = 1801,				-- 小助手-升级
	helper_earn = 1802,					-- 小助手-赚钱
	helper_equip = 1803,				-- 小助手-装备
	helper_strength= 1804,				-- 小助手-变强
	helper_energy = 1805,				-- 小助手-活力

	goddess_info = 1900,				-- 女神信息
	goddess_camp = 1901,				-- 女神阵营-屏蔽
	goddess_shouhu = 1902,				-- 女神守护
	goddess_shengong = 1903,			-- 女神神弓 =>光环
	goddess_shenyi = 1904,				-- 女神神翼 =>法阵
	goddess_shengwu = 1905,				-- 女神圣物
	goddess_gongming = 1915,			-- 女神共鸣
	goddess_defense = 1906,				-- 女神塔防
	goddess_huanhua = 1907,				-- 女神幻化

	yu_hun = 2000,						-- 御魂
	yu_hun_info = 20010,				-- 御魂--御魂
	yu_hun_expedition = 20011,			-- 御魂--远征
	yu_hun_exchange = 20012,			-- 御魂--兑换

	magic_card = 2200,					-- 魔卡
	magic_lottery = 22010,				-- 魔卡--抽奖
	magic_exchange = 22011,				-- 魔卡--兑换

	treasure_choujiang = 2300,			-- 极品寻宝
	treasure_exchange = 2301,			-- 寻宝兑换
	treasure_warehouse = 2302,			-- 寻宝仓库
	treasure_choujiang2 = 2303,			-- 巅峰寻宝
	treasure_choujiang3 = 2304,			-- 至尊寻宝

	sword_art_online = 2500,			-- 刀剑神域

	rechare_info = 2600,				-- 充值
	rechare_power = 2601,				-- 充值--权限
	rechare_level_invest = 2602,		-- 充值--等级投资
	rechare_month_invest = 2603,		-- 充值--月卡投资

	exchange_mojing = 2700,				-- 兑换--魔晶
	exchange_shengwang = 2701,			-- 兑换--声望
	exchange_rongyao = 2702,			-- 兑换--武勋
	exchange_guanghui = 2703,			-- 兑换--魂玉
	exchange_xianjing = 2704,			-- 兑换--秘宝
	exchange_yihuo = 2705,				-- 兑换--异火
	exchange_yushi = 2706,				-- 兑换--玉石
	exchange_jingling = 2707,			-- 兑换--仙宠
	exchange_hunjing = 2708,			-- 兑换--魂晶
	exchange_guildcontribute = 2709,	-- 兑换--仙盟贡献
	exchange_weiji = 2710,				-- 兑换--微计

	map_local = 2800,					-- 本地地图
	map_world = 2801,					-- 世界地图

	kaifu_jizi = 102155,				-- 开服活动集字活动

	rune_inlay = 6100,						-- 符文-符文镶嵌
	rune_analyze = 6101,					-- 符文-符文分解
	rune_exchange = 6102,					-- 符文-符文兑换
	rune_treasure = 6103,					-- 符文-符文寻宝
	rune_compose = 6104,					-- 符文-符文合成
	rune_tower = 6105,						-- 符文-符文塔
	rune_zhuling = 6106,					-- 符文-符文祭炼
	rune_totalshow = 6107,					-- 符文-符文总览

	setting_xianshi = 1028,				-- 设置显示
	setting_system = 2028,				-- 设置系统
	setting_notice = 3028,				-- 设置公告
	setting_custom = 4028,				-- 设置客服

	seven_login_goddess = 2900,			-- 7天登录女神界面

	shen_ge_shen_ge = 3000,				-- 神格
	shen_ge_inlay = 3001,				-- 神格镶嵌
	shen_ge_bless = 3002,				-- 神格祈福
	shen_ge_group = 3003,				-- 神格组合
	shen_ge_compose = 3004,				-- 神格合成
	shen_ge_zhangkong = 3005,			-- 神格掌控
	shen_ge_godbody = 3006,				-- 神格身躯

	hunqi = 3010,						-- 魂器
	hunqi_content = 3011,				-- 魂器魂器
	hunqi_damo = 3012,					-- 魂器打磨
	hunqi_bao = 3013,					-- 魂器宝藏
	hunqi_hunyin = 3014,				-- 魂器魂印
	hunqi_xilian = 30143,	        	-- 魂器洗练

	shengxiao = 3020,					-- 星座
	shengxiao_uplevel = 3021,			-- 星座升级
	shengxiao_equip = 3022,				-- 星座装备
	shengxiao_piece = 3023,				-- 星座星途
	shengxiao_spirit = 3024,			-- 星座星灵
	shengxiao_starsoul = 3025,			-- 星座星灵

	shenbing = 3031,					--神器神兵
	baojia = 3032,						--神器宝甲
	fenjie = 3033,						--神器分解


	shenyin_shenyin = 3100,				-- 神印--神印
	shenyin_liehun = 3101,				-- 神印--猎魂
	shenyin_qianghua = 3102,			-- 神印--强化
	shenyin_xilian = 3103,				-- 神印--洗练
	shenyin_tianxiang = 3104,			-- 神印--天象
	shenyin_exchange = 3105,			-- 神印--兑换

	shenhua_pianzhang = 3200,			-- 神话--篇章
	shenhua_gongming = 3201,			-- 神话--冥想

	-- shop_chengzhang = 4000,				--商城-·成长
	-- shop_baoshi = 4001,					--商城--宝石
	-- shop_bind = 4002,					--商城--绑定
	-- shop_youhui = 4003,					--商城--优惠

	yule_fishing = 5010,				--娱乐-钓鱼
	yule_go_pawn = 5020,				--娱乐-幻境寻宝

	mining_mining = 6001,				--决斗场-挖矿
	mining_sea = 6002,					--决斗场-航海
	mining_challenge = 6003,			--决斗场-挑衅

	kaifu_invest_boss = 7001,			--开服投资-Boss投资
	kaifu_invest_active = 7002,			--开服投资--活跃
	kaifu_invest_competition = 7003,	--开服投资--比拼

	welfare_sign_in = 8001,				--福利-签到
	welfare_level = 8002,				--福利-等级豪礼
	welfare_find = 8003,				--福利-找回
	welfare_exchange = 8004,			--福利-兑换
	welfare_goldturn = 8005,			--福利-钻石转盘

	arena_view = 9001,					--竞技-竞技场
	arena_rank_view = 9002,				--竞技-排名
	arena_tupo_view = 9003,				--竞技-突破

	kf_arena_view = 9101,				--跨服论剑
	kf_arena_rank_view = 9102,			--跨服论剑排名

	kuafu_liujie = 10001,
	liujie_bossinfo = 10002,
	liujie_show = 10003,

	mount_huan_hua = 11001,				--坐骑幻化
	wing_huan_hua = 11002,				--羽翼幻化
	fashion_huan_hua = 11003,			--时装幻化
	wuqi_huan_hua = 11004,				--神兵幻化
	fabao_huan_hua = 11005,				--法宝幻化
	foot_huan_hua = 11006,				--足迹幻化
	fight_mount_huan_hua = 11007,		--战骑幻化
	halo_huan_hua = 11008,				--光环幻化
	jinjie_zhuangbei = 11009,			--进阶装备
	appearance_equip_view = 110010,		--外观装备
	shenci_wing_huan_hua = 110011,		--羽翼幻化
	shenci_fightmount_huan_hua = 110012,		--战骑幻化
	shenci_mount_huan_hua = 110013,		--坐骑幻化

	check_jue_se = 12001,				--角色查看
	check_mount = 12002,				--坐骑查看
	check_wing = 12003,					--羽翼查看
	check_halo = 12004,					--光环查看
	check_fight_mount = 12005,			--战骑查看
	check_spirit = 12006,				--精灵查看
	check_goddess = 12007,				--女神查看
	check_shengong = 12008,				--神弓查看
	check_shengyi = 12009,				--神翼查看
	check_foot = 12010,					--足迹查看
	check_cloak = 12011,				--披风查看

	rank_tab = 13001,					--排名
	rank_ming_tab = 13002,				--名人堂
	rank_meili_tab = 13003,				--魅力

	kuafu1v1_pipei = 14001,				--跨服1v1匹配
	kuafu1v1_gongxun = 14002,			--跨服1v1功勋
	kuafu1v1_reward = 14003,			--跨服1v1奖励
	kuafu1v1_rank = 14004,				--跨服1v1百强

	little_pet_home = 15001,			-- 家园
	little_pet_feed = 15002,			-- 喂养
	little_pet_toy = 15003,				-- 玩具
	little_pet_shop = 15004,			-- 商店
	little_pet_exchange = 15005,		-- 兑换

	clothespress_suit = 10041,			-- 衣橱套装
	clothespress_looks = 10042,			-- 衣橱穿搭
	clothespress_dress = 10043,			-- 衣橱装扮
	clothespress_exchange = 10044,		-- 衣橱兑换

	kuafu3v3_pipei = 16001,				-- 跨服3v3匹配
	kuafu3v3_gongxun = 16002,			-- 跨服3v3功勋
	kuafu3v3_reward = 16003,			-- 跨服3v3奖励
	kuafu3v3_rank = 16004,				-- 跨服3v3百强


	one_yuan_panel_snatch = 16010,		-- 一元夺宝-奖券
	one_yuan_panel_integral = 16011,	-- 一元夺宝-夺宝
	one_yuan_panel_log = 16012,			-- 一元夺宝-积分
	one_yuan_panel_ticket = 16013,		-- 一元夺宝-记录

	orange_suit_collect = 17001, 		-- 套装收集-橙装收集
	red_suit_collect = 17002, 			-- 套装收集-红装收集

	bian_shen_msg = 18001, 				-- 仙域-变身-信息
	bian_shen_qian_neng = 18002,		-- 仙域-变身-潜能
	bian_shen_qing_shen = 18003,		-- 仙域-变身-请神
	bian_shen_equip = 18004,			-- 仙域-变身-装备
	bian_shen_strengthen = 18005,		-- 仙域-变身-强化

	shop_youhui = 19001,				-- 商城-·优惠
	shop_chengzhang = 19002,			-- 商城--成长
	shop_bind = 19003,					-- 商城--绑定
	shop_normal = 19004,				-- 商城--常用

	send_gift_zengsong = 20001,         -- 赠送
	send_gift_record = 20002,            -- 记录


	douqi_grade = 21001,				-- 斗气-阶段
	douqi_equip = 21002,				-- 斗气-装备
	douqi_refine = 21003, 				-- 斗气-炼制
	xing_xiang = 30001,					-- 星象
}

--一个个小ui名字，用于引导中指向某个ui
GuideUIName = {
	Tab = "tab",										-- 标签，参数：第几个索引（1开始）
	CloseBtn = "BtnClose",								-- 关闭按钮

	MainUIRoleHead = "menu_icon",						-- 主界面-菜单按钮
	MainUIRightShrink = "shrink_button",				-- 主界面-右上收缩按钮
	MainUIRolePlayer = "Player",						-- 主界面-人物按钮
	MainUIForge = ViewName.Forge,						-- 主界面-锻造按钮
	MainUIAdvance = ViewName.Advance,					-- 主界面-形象按钮
	MainUIGoddress = ViewName.Goddess,					-- 主界面-女神按钮
	MainUIBaoju = "button_baoju",						-- 主界面-宝具按钮
	MainUISpirit = "button_spiritview",					-- 主界面-精灵按钮
	MainUICompose = "button_compose",					-- 主界面-合成按钮
	MainUIGuild = "button_guild",						-- 主界面-公会按钮
	MainUIScoiety = "button_scoiety",					-- 主界面-社交按钮
	MainUIMarriage = "button_marriage",					-- 主界面-结婚按钮
	MainUIRank = "button_ranking",						-- 主界面-排行榜按钮
	MainUIEchange = "button_exchange",					-- 主界面-兑换按钮
	MainUIMarket = "button_market",						-- 主界面-市场按钮
	MainUIShop = "button_shop",							-- 主界面-商城按钮
	MainUISetting = "button_setting",					-- 主界面-设置按钮
	MainUIDailyCharge = "button_daily_charge",			-- 主界面-每日首冲按钮
	MainUIFirstCharge = "button_firstchargeview",		-- 主界面-首冲按钮
	MainUISevenLogin = "button_logingift7view",			-- 主界面-七天登录按钮
	MainUISingleFuBen = "button_fuben",					-- 主界面-单人副本按钮
	MainUIXunBao = "button_treasure",					-- 主界面-寻宝按钮
	MainUIZhuanSheng = "button_reincarnation",			-- 主界面-转生按钮
	MainUIBtnDaily = "btn_daily",						-- 主界面-每日必做按钮
	MainUIBtnTarget = "button_mieshizhizhan",			-- 主界面-灭世历练按钮
	MainUIJingCaiHuoDong = "button_kaifuactivityview",	-- 主界面-精彩活动
	MainUIBossHunter = "btn_boss_hunter",				-- 主界面-精彩活动列表（boss猎手按钮）
	MainUIExperience = "btn_experience",				-- 主界面-灭世之战列表（灭世历练按钮）
	MainUIBossIcon = "boss",							-- 主界面-Boss按钮
	MainUIButtonPackage = "ButtonPackage",				-- 主界面-背包按钮
	MainUICorssRank = "MainUICorssRank",				-- 主界面-跨服排行按钮
	BtnBianShen = "BtnBianShen",						-- 主界面-变身按钮
	QingGongBtn = "qinggong_btn",						-- 主界面-轻功按钮
	QingGongDownBtn = "qinggong_down_btn",

	AdvanceMountUp = "StartButton",						-- 形象进阶-坐骑进阶按钮
	AdvanceWingUp = "wing_start_up",					-- 形象进阶-羽翼进阶按钮

	GodessUpBtn = "upgrade_btn",						-- 女神-女神升级按钮
	GodessActiveBtn = "godess_active_btn",				-- 女神-女神激活按钮
	GodessLineUpFight = "godess_line_up_fight",			-- 女神-出战按钮
	GodessIcon1 = "godess_icon1",						-- 女神-第一位女神
	GoddessSkill = "goddess_skill",						-- 女神-技能

	MountAttrBtn = "challenge_btn",						-- 副本-坐骑副本挑战
	QualityFbBtn = "BtnCanChallenge",					-- 副本-品质副本挑战
	QhallengeFbBtn = "BtnChallenge",					-- 副本-守护副本挑战
	ExpZhuduiBtn = "BtnZuDui",							-- 副本-经验副本组队
	WeaponChallenge = "ButtonChallenge",				-- 副本-武器副本挑战
	ButtonChallenge = "ButtonChallenge_f",				-- 副本-防具副本挑战
	StroyFbChangeBtn = "stroyfb_change_btn",			-- 副本-剧情副本第一个挑战按钮
	TowerChallenge = "tower_challenge",					-- 副本-勇者之塔挑战按钮
	ToggleYuansu = "toggle_yuansu",						-- 副本-元素试炼标签按钮
	YuanSuAttackButton = "yuansu_attack_button",		-- 副本-元素试炼进入副本按钮
	ToggleWujin = "toggle_wujin",						-- 副本-无尽炼狱标签按钮
	WujinEnterButton = "wujin_enter_button",			-- 副本-无尽炼狱发起进攻按钮

	FriendLotAdd = "friend_lot_add",					-- 社交-好友批量添加按钮
	FriendRecAutoAdd = "friend_rec_auto_add",			-- 社交-好友推荐一键添加按钮

	BaoJuGoToJinJieFuBen = "baoju_goto_jinjie_fuben",	-- 宝具-活跃前往进阶副本按钮
	BaojuGotoDaily = "baoju_goto_daily",				-- 宝具-活跃日常任务按钮

	-- ForgeFristEquipItem = "frist_equip_item",		-- 锻造-第一个装备格子
	ForgeUpStarBtn = "UpStarBtn",						-- 锻造-升星按钮
	ForgeAdvanceBtn = "AdvanceBtn",						-- 锻造-升星按钮
	ForgeStrengthenTab = "forge_strengthen",			-- 锻造-强化
	ForgeBtnStrength = "BtnStrength",					-- 锻造-强化按钮
	ForgeBtnPromoteBtn = "PromoteBtn",					-- 锻造-品质
	ForgeAdvancetn = "forge_advance",					-- 锻造升级

	TreasureOneTimesBtn = "one_times_btn",				-- 寻宝-寻宝一次按钮
	TreasureBackWareHouseBtn = "back_warehouse_btn",	-- 寻宝-返回仓库按钮
	TreasureGetAllBtn = "get_all_btn",					-- 寻宝-一键取出按钮

	ZhuanShengBtn = "zhuanzhi_recieve",					-- 转生-转生按钮

	RecycleButton = "RecycleButton",					-- 角色-装备回收按钮
	RecycleAndCloseButton = "recycle_and_closebutton",	-- 角色-立即回收按钮
	TabEquip = "tab_equip",								-- 角色-装备标签

	SevenDayRewardBtn = "reward_btn",					-- 七天登录-领取按钮

	GuildAutoEnter = "guild_auto_enter_btn",			-- 公会--快速加入

	BossGuideFatigue = "boss_fatigue",					-- Boss-引导疲劳值
	BtnToAttach = "BtnToAttach",						-- Boss-立即前往
	BossPersonalCha = "personal_cha",					-- 个人Boss-立即前往

	PersonalGoalRewardBtn = "target_reward_btn",		-- 灭世之战-领取奖励按钮

	ExchangeMoJingFirstItem = "mojing_first_item",		-- 兑换-魔晶第一个物品
	ExchangeTipsBtnBuy = "exchange_btn_buy",			-- 兑换tips-兑换按钮

	TaskDailyItem = "task_daily_item",					-- 任务-日常任务
	TaskZhiItem = "task_zhi_item",						-- 任务-支线任务

	MiningBtnChallenge = "mining_btn_challenge",		-- 决斗场-挑战按钮

	ArenaFirsRoleStand = "first_role_stand",			-- 竞技场-最差那个玩家挑战按钮
	EnterButton = "EnterButton",						-- 战魂塔立即进入
	RuneSlot1 = "slot_1",								-- 战魂塔附魂第一个格子
	FishingBtn = "fishing_btn",							-- 钓鱼按钮
	StartFishing = "start_fishing",						-- 开始钓鱼

	SpiritChoose = "spirit_choose",						-- 精灵背包
	SpiritUse = "spirit_use",							-- 装备
	MainUiZuoqi = "zuoqi_button",						-- 坐骑

	OneTimesBtn = "one_times_btn",						-- 寻宝一次
	BackWarehouseBtn = "back_warehouse_btn",			-- 返回仓库
	GetAllBtn = "get_all_btn",							-- 一键取出

	BianShenActive = "BianShenActive",					-- 变身激活
	BianShenUse = "BianShenUse",						-- 变身激活

	OffLineExpTop = "OffLineExpTop",					-- 离线引导
	OffLineExpDown = "OffLineExpDown",					-- 离线引导
}