local InitLoadingData = {
	Reminding = {
		"7级开启坐骑系统，骑上马，体验飞一般的感觉",
		"57级开启羽翼系统，开启飞翔之旅",
		"成为VIP2，可以免费双倍完成经验任务哦~",
		"首充1元，即送红色3星武器，绝版酷炫坐骑",
		"开服嘉年华，每天定个小目标，领走绝版形象哦",
		"80级就可以结婚啦，浪漫婚宴，可爱宝宝，趣味家园等你来体验~",
		"120级开启转职，开启高阶装备，高阶技能！",
		"BOSS地图凶险万分，小心他人攻击！当然你也可以选择打劫~",
		"记得去每日必做里看看自己还有什么没完成的",
		"经验本、双倍护送和经验跑环任务，是快速升级的有效途径",
		"挂机打怪之前记得使用经验药哦",
		"商店淘宝，折扣多多，还有几率刷出顶级仙女！",
		"挑战战魂塔，可解锁更多战魂，更高等级上限",
		"爬塔可获得大量境界令牌，还能解锁传世名剑！",
		"采集地图上的蛋可获得珍稀宠物，还有几率触发BOSS呢！",
		"市场上很多奇珍异宝，记得多逛逛哦",
	},
	RawImages = {
		{"uis/rawimages/sceneloading_bg_1", "sceneloading_bg_1.jpg"},
		{"uis/rawimages/sceneloading_bg_12", "sceneloading_bg_12.jpg"},
	},
	SceneImages = {
		{"uis/rawimages/sceneloading_bg_1", "sceneloading_bg_1.jpg"},
		{"uis/rawimages/sceneloading_bg_2", "sceneloading_bg_2.jpg"},
		{"uis/rawimages/sceneloading_bg_4", "sceneloading_bg_4.jpg"},
		{"uis/rawimages/sceneloading_bg_12", "sceneloading_bg_12.jpg"},
	},
	SceneDayImages = {
	[1]={
		{"uis/rawimages/sceneloading_bg_1", "sceneloading_bg_1.jpg"},
		{"uis/rawimages/sceneloading_bg_3", "sceneloading_bg_3.jpg"},
		{"uis/rawimages/sceneloading_bg_4", "sceneloading_bg_4.jpg"},
		{"uis/rawimages/sceneloading_bg_5", "sceneloading_bg_5.jpg"},
		{"uis/rawimages/sceneloading_bg_8", "sceneloading_bg_8.jpg"},
		{"uis/rawimages/sceneloading_bg_10", "sceneloading_bg_10.jpg"},
		{"uis/rawimages/sceneloading_bg_11", "sceneloading_bg_11.jpg"},
		{"uis/rawimages/sceneloading_bg_12", "sceneloading_bg_12.jpg"},},
	[2]={
		{"uis/rawimages/sceneloading_bg_1", "sceneloading_bg_1.jpg"},
		{"uis/rawimages/sceneloading_bg_3", "sceneloading_bg_3.jpg"},
		{"uis/rawimages/sceneloading_bg_4", "sceneloading_bg_4.jpg"},
		{"uis/rawimages/sceneloading_bg_5", "sceneloading_bg_5.jpg"},
		{"uis/rawimages/sceneloading_bg_8", "sceneloading_bg_8.jpg"},
		{"uis/rawimages/sceneloading_bg_9", "sceneloading_bg_9.jpg"},
		{"uis/rawimages/sceneloading_bg_10", "sceneloading_bg_10.jpg"},
		{"uis/rawimages/sceneloading_bg_11", "sceneloading_bg_11.jpg"},
		{"uis/rawimages/sceneloading_bg_12", "sceneloading_bg_12.jpg"},},
	[3]={
		{"uis/rawimages/sceneloading_bg_1", "sceneloading_bg_1.jpg"},
		{"uis/rawimages/sceneloading_bg_2", "sceneloading_bg_2.jpg"},
		{"uis/rawimages/sceneloading_bg_3", "sceneloading_bg_3.jpg"},
		{"uis/rawimages/sceneloading_bg_4", "sceneloading_bg_4.jpg"},
		{"uis/rawimages/sceneloading_bg_5", "sceneloading_bg_5.jpg"},
		{"uis/rawimages/sceneloading_bg_8", "sceneloading_bg_8.jpg"},
		{"uis/rawimages/sceneloading_bg_9", "sceneloading_bg_9.jpg"},
		{"uis/rawimages/sceneloading_bg_10", "sceneloading_bg_10.jpg"},
		{"uis/rawimages/sceneloading_bg_11", "sceneloading_bg_11.jpg"},
		{"uis/rawimages/sceneloading_bg_12", "sceneloading_bg_12.jpg"},},
	[4]={
		{"uis/rawimages/sceneloading_bg_1", "sceneloading_bg_1.jpg"},
		{"uis/rawimages/sceneloading_bg_2", "sceneloading_bg_2.jpg"},
		{"uis/rawimages/sceneloading_bg_3", "sceneloading_bg_3.jpg"},
		{"uis/rawimages/sceneloading_bg_4", "sceneloading_bg_4.jpg"},
		{"uis/rawimages/sceneloading_bg_5", "sceneloading_bg_5.jpg"},
		{"uis/rawimages/sceneloading_bg_8", "sceneloading_bg_8.jpg"},
		{"uis/rawimages/sceneloading_bg_9", "sceneloading_bg_9.jpg"},
		{"uis/rawimages/sceneloading_bg_10", "sceneloading_bg_10.jpg"},
		{"uis/rawimages/sceneloading_bg_11", "sceneloading_bg_11.jpg"},
		{"uis/rawimages/sceneloading_bg_12", "sceneloading_bg_12.jpg"},},
	[5]={
		{"uis/rawimages/sceneloading_bg_1", "sceneloading_bg_1.jpg"},
		{"uis/rawimages/sceneloading_bg_2", "sceneloading_bg_2.jpg"},
		{"uis/rawimages/sceneloading_bg_3", "sceneloading_bg_3.jpg"},
		{"uis/rawimages/sceneloading_bg_4", "sceneloading_bg_4.jpg"},
		{"uis/rawimages/sceneloading_bg_5", "sceneloading_bg_5.jpg"},
		{"uis/rawimages/sceneloading_bg_6", "sceneloading_bg_6.jpg"},
		{"uis/rawimages/sceneloading_bg_7", "sceneloading_bg_7.jpg"},
		{"uis/rawimages/sceneloading_bg_8", "sceneloading_bg_8.jpg"},
		{"uis/rawimages/sceneloading_bg_9", "sceneloading_bg_9.jpg"},
		{"uis/rawimages/sceneloading_bg_10", "sceneloading_bg_10.jpg"},
		{"uis/rawimages/sceneloading_bg_11", "sceneloading_bg_11.jpg"},
		{"uis/rawimages/sceneloading_bg_12", "sceneloading_bg_12.jpg"},},
	[6]={
		{"uis/rawimages/sceneloading_bg_1", "sceneloading_bg_1.jpg"},
		{"uis/rawimages/sceneloading_bg_2", "sceneloading_bg_2.jpg"},
		{"uis/rawimages/sceneloading_bg_3", "sceneloading_bg_3.jpg"},
		{"uis/rawimages/sceneloading_bg_4", "sceneloading_bg_4.jpg"},
		{"uis/rawimages/sceneloading_bg_5", "sceneloading_bg_5.jpg"},
		{"uis/rawimages/sceneloading_bg_6", "sceneloading_bg_6.jpg"},
		{"uis/rawimages/sceneloading_bg_7", "sceneloading_bg_7.jpg"},
		{"uis/rawimages/sceneloading_bg_8", "sceneloading_bg_8.jpg"},
		{"uis/rawimages/sceneloading_bg_9", "sceneloading_bg_9.jpg"},
		{"uis/rawimages/sceneloading_bg_10", "sceneloading_bg_10.jpg"},
		{"uis/rawimages/sceneloading_bg_11", "sceneloading_bg_11.jpg"},
		{"uis/rawimages/sceneloading_bg_12", "sceneloading_bg_12.jpg"},},
	[7]={
		{"uis/rawimages/sceneloading_bg_1", "sceneloading_bg_1.jpg"},
		{"uis/rawimages/sceneloading_bg_2", "sceneloading_bg_2.jpg"},
		{"uis/rawimages/sceneloading_bg_3", "sceneloading_bg_3.jpg"},
		{"uis/rawimages/sceneloading_bg_4", "sceneloading_bg_4.jpg"},
		{"uis/rawimages/sceneloading_bg_5", "sceneloading_bg_5.jpg"},
		{"uis/rawimages/sceneloading_bg_6", "sceneloading_bg_6.jpg"},
		{"uis/rawimages/sceneloading_bg_7", "sceneloading_bg_7.jpg"},
		{"uis/rawimages/sceneloading_bg_8", "sceneloading_bg_8.jpg"},
		{"uis/rawimages/sceneloading_bg_9", "sceneloading_bg_9.jpg"},
		{"uis/rawimages/sceneloading_bg_10", "sceneloading_bg_10.jpg"},
		{"uis/rawimages/sceneloading_bg_11", "sceneloading_bg_11.jpg"},
		{"uis/rawimages/sceneloading_bg_12", "sceneloading_bg_12.jpg"},},
	[8]={
		{"uis/rawimages/sceneloading_bg_1", "sceneloading_bg_1.jpg"},
		{"uis/rawimages/sceneloading_bg_2", "sceneloading_bg_2.jpg"},
		{"uis/rawimages/sceneloading_bg_4", "sceneloading_bg_4.jpg"},
		{"uis/rawimages/sceneloading_bg_5", "sceneloading_bg_5.jpg"},
		{"uis/rawimages/sceneloading_bg_6", "sceneloading_bg_6.jpg"},
		{"uis/rawimages/sceneloading_bg_7", "sceneloading_bg_7.jpg"},
		{"uis/rawimages/sceneloading_bg_8", "sceneloading_bg_8.jpg"},
		{"uis/rawimages/sceneloading_bg_9", "sceneloading_bg_9.jpg"},
		{"uis/rawimages/sceneloading_bg_10", "sceneloading_bg_10.jpg"},
		{"uis/rawimages/sceneloading_bg_12", "sceneloading_bg_12.jpg"},},

	},
	UpdateText = {
		"发现新版本,正在更新中。",
		"正在加载新地图中。",
	},
}

return InitLoadingData