
-- 需要require的文件列表
local lua_file_list = {
	"systool/systool",

	"utils/bit",
	"utils/ui",
	"utils/timeutil",
	"utils/operate_frequency",
	"utils/xmlutil",
	"utils/richtext_util",
	"utils/playerprefs_util",

	"gamenet/gamenet",

	"config/config_other",
	"config/config_chatfilter",
	"config/config_usernamefilter",
	"config/config_map",
	"config/config_manager",
	"config/errorcode",

	"core/draw_obj",
	"core/gamemap_helper",

	"manager/preload_manager",

	"game/common/common_const",
	"game/common/game_enum",
	"game/common/base_controller",
	"game/common/base_event",
	"game/common/base_view",
	"game/common/global_events",
	"game/common/modules_controller",
	"game/common/res_path",
	"game/common/common_struct",
	"game/common/color_def",

	"config/auto_new/item/gift_auto",
	"config/auto_new/item/equipment_auto",
	"config/auto_new/item/other_auto",
	"config/auto_new/item/expense_auto",
	"config/auto_new/item/virtual_auto",

	-- 常用配置表
	"config/auto_new/sorting_config_auto",
	"config/auto_new/roleskill_auto",
	"config/auto_new/tasklist_auto",
	"config/auto_new/monster_auto",
	"config/auto_new/mount_auto",
	"config/auto_new/wing_auto",
	"config/auto_new/xiannvconfig_auto",
	"config/auto_new/jingling_auto",
	"config/auto_new/rune_system_cfg_auto",
	"config/auto_new/tuitu_fb_auto",
	"config/auto_new/shenge_system_cfg_auto",
	"config/auto_new/equipforge_auto",
	"config/auto_new/randactivityconfig_1_auto",
	"config/auto_new/pasture_spirit_auto",
	"config/auto_new/xunzhangconfig_auto",
	"config/auto_new/equipmentsuit_auto",
	"config/auto_new/randactivityconfig_auto",
	"config/auto_new/chinese_zodiac_cfg_auto",
	"config/auto_new/campconfg_auto",
	"config/auto_new/duanzaosuit_auto",
	"config/auto_new/lieming_auto",
	"config/auto_new/pet_cfg_auto",
	"config/auto_new/halo_auto",
	"config/auto_new/shizhuangcfg_auto",
	"config/auto_new/rolegoalconfig_auto",

	--需要放在ctrl 类前，common 后
	"language/language",

	"manager/avatarmanager",
	"manager/audioservice",
	"manager/loading_priority_manager",
	"manager/effect_manager",
	"manager/userdefault",
	"game/sharedata/gamevo_manager",
	"gameui/game_ui",
	"game/tips/tips_def",
	"game/time/time_ctrl",
	"game/clientcmd/client_cmd_ctrl",
	"game/login/login_ctrl",
	"game/scene/scene",
	"game/scene/actor/actor_config_data",
	"game/mainui/mainui_ctrl",
	"game/sysmsg/sysmsg_ctrl",
	"game/tips/tips_ctrl",
	"game/tips/tips_trigger_ctrl",
	"game/player/player_ctrl",
	"game/story/story_ctrl",
	"game/fight/fight_ctrl",
	"game/guaji/guaji_ctrl",
	"game/task/task_ctrl",
	"game/tianshu/tianshu_ctrl",
	"game/other/other_ctrl",
	"game/chat/chat_ctrl",
	"game/chat/cool_chat_ctrl",
	"game/autovoice/voice_ctrl",
	"game/hongbao/hongbao_ctrl",
	"game/guide/guide_ctrl",
	"game/player/package/package_ctrl",
	"game/player/title/title_ctrl",
	"game/player/skill/skill_ctrl",
	"game/player/wing/wing_ctrl",
	"game/player/mojie/mojie_ctrl",
	"game/player/luoshu/luoshu_ctrl",
	"game/player/equipment_shen/equipmentshen_ctrl",
	"game/player/tulong_equip/tulong_equip_ctrl",
	"game/player/zhuanzhi/zhuanzhi_ctrl",


	"game/forge/forge_ctrl",

	
	"game/kuafu_xiuluo_tower/kuafu_xiuluo_tower_ctrl",
	"game/advance/advance_ctrl",
	"game/baoju/baoju_ctrl",
	"game/myth/myth_ctrl",
	"game/baoju/achieve/achieve_ctrl",
	"game/baoju/zhibao/zhibao_ctrl",
	"game/baoju/jingjie/jingjie_ctrl",
	"game/baoju/medal/medal_ctrl",
	"game/welfare/welfare_ctrl",
	"game/camp/camp_ctrl",
	"game/goddess/goddess_ctrl",
	"game/goddess/shenyi/shenyi_ctrl",
	"game/goddess/shenyi/huanhua/shenyi_huan_hua_ctrl",
	"game/goddess/shengong/shengong_ctrl",
	"game/goddess/shengong/shengonghuanhua/shengong_huan_hua_ctrl",
	"game/advance/mount/mount_ctrl",
	"game/xianshilianchong/xian_shi_lian_chong_ctrl",
	-- "game/advance/equipupgrade/advance_equip_up_ctrl",
	-- "game/advance/mount/mounthuanhua/mount_huan_hua_ctrl",
	-- "game/advance/fightmount/fightmounthuanhua/fight_mount_huan_hua_ctrl",
	"game/advance/wing/wing_ctrl",
	-- "game/advance/wing/winghuanhua/wing_huan_hua_ctrl",
	"game/advance/foot/foot_ctrl",
	-- "game/advance/foot/foothuanhua/foot_huan_hua_ctrl",
	"game/advance/halo/halo_ctrl",
	-- "game/advance/halo/halohuanhua/halo_huan_hua_ctrl",
	"game/advance/fashion/fashion_ctrl",
	-- "game/advance/fashion/wuqi_huanhua/wuqi_huan_hua_ctrl",
	"game/advance/ling_ren/lingren_ctrl",
	"game/shenqi/shenqi_ctrl",

	--夫妻家园
	"game/couple_home/couple_home_ctrl",
	"game/couple_home/couple_home_home/couple_home_home_ctrl",
	"game/couple_home/couple_home_shop/couple_home_shop_ctrl",

	"game/guild/guild_ctrl",
	"game/guild/guild_bonfire/guild_bonfire_ctrl",
	"game/clash_territory/clash_territory_ctrl",
	"game/element_battle/element_battle_ctrl",
	"game/goddess/huanhua/goddess_huanhua_ctrl",
	"game/market/market_ctrl",
	"game/marriage/marriage_ctrl",
	"game/marriage/baobao/baobao_ctrl",
	"game/rank/rank_ctrl",
	"game/fuben/fu_ben_ctrl",
	"game/gao_zhan_fu_ben/gao_zhan_ctrl",
	"game/scoiety/scoiety_ctrl",
	"game/send_gift/send_gift_ctrl",
	"game/check/check_ctrl",
	"game/compose/compose_ctrl",
	"game/activity/activity_ctrl",
	"game/daily_task_fb/daily_task_fb_ctrl",
	"game/boss/boss_ctrl",
	"game/guild_fight/guild_fight_ctrl",
	"game/dafuhao/dafuhao_ctrl",
	"game/exchange/exchange_ctrl",
	"game/city_combat/city_combat_ctrl",
	"game/shop/shop_ctrl",
	"game/setting/setting_ctrl",
	"game/treasure/treasure_ctrl",
	"game/leiji_recharge/leiji_recharge_ctrl",
	"game/trade/trade_ctrl",
	"game/map/map_ctrl",
	"game/revive/revive_ctrl",
	"game/spirit/spirit_ctrl",
	"game/vip/recharge_ctrl",
	"game/vip/vip_ctrl",
	"game/kuafu_1v1/kuafu1v1_ctrl",
	"game/xingxiang/xingxiang_ctrl",
	"game/kuafu_pvp/kf_pvp_ctrl",
	"game/cross_server/cross_server_ctrl",
	"game/cross_rank/cross_rank_ctrl",
	"game/yunbiao/yunbiao_ctrl",
	"game/tianshenhuti/tianshenhuti_ctrl",
	"game/daycounter/daycounter_ctrl",
	"game/skymoney/sky_money_ctrl",
	"game/flowers/flowers_ctrl",
	"game/zhuaguiview/zhuagui_ctrl",
	"game/scratch_ticket/scratch_ticket_ctrl",
	"game/kaifuactivity/kaifu_activity_ctrl",
	"game/treasure_bowl/treasure_bowl_ctrl",
	"game/hot_spring_chat/hot_spring_chat_ctrl",
	"game/logingift7/login_gift7_ctrl",
	"game/guild_mijing/guild_mijing_ctrl",
	"game/daily_charge/daily_charge_ctrl",
	"game/ancient_relics/ancient_relics_ctrl",
	"game/rebate/rebate_ctrl",
	"game/tomb_explore/tomb_explore_ctrl",
	"game/first_charge/first_charge_ctrl",
	"game/cross_crystal/cross_crystal_ctrl",
	"game/free_gift/free_gift_ctrl",
	"game/advance/huashen/huashen_ctrl",
	"game/jinjie_reward/jinjie_reward_ctrl",
	"game/zhizun_recharge_rank/zhizun_recharge_rank_ctrl",
	-- "game/pet/pet_ctrl",
	"game/player/zhuansheng/zhuansheng_ctrl",
	"game/advance/fightmount/fight_mount_ctrl",
	"game/player/reincarnation/reincarnation_ctrl",
	"game/open_fun/open_fun_ctrl",
	"game/shenshou/shenshou_ctrl",
	"game/hpbag/hp_bag_ctrl",
	"game/funfuben/expresion_fu_ben_ctrl",
	"game/xinshou/welcome_ctrl",
	"game/molong_mibao/molong_mibao_ctrl",
	"game/marry_me/marry_me_ctrl",
	"game/gold_member/gold_member_ctrl",
	"game/dalegou/dalegou_ctrl",
	"game/discount/discount_ctrl",
	"game/competition_activity/competition_activity_ctrl",
	"game/biping_activity/biping_activity_ctrl",
	-- "game/personal_goals/personal_goals_ctrl",
	"game/rune/rune_ctrl",
	"game/guajita/guajita_ctrl",
	"game/rand_system/rand_system_ctrl",
	"game/shen_ge/shen_ge_ctrl",
	"game/wabao/wabao_ctrl",
	"game/relic/relic_ctrl",
	"game/arena/arena_ctrl",
	"game/kfarena/kf_arena_ctrl",
	"game/puzzle/puzzle_ctrl",
	"game/shen_ge/hun_qi/hunqi_ctrl",
	"game/recharge_rank/recharge_rank_ctrl",
	"game/consume_rank/consume_rank_ctrl",
	"game/symbol/symbol_ctrl",
	"game/juhuasuan/juhuasuan_ctrl",
	"game/three_piece/three_piece_ctrl",
	"game/fast_charging/fast_charging_ctrl",
	"game/shen_ge/shengxiao/shengxiao_ctrl",
	"game/shen_ge/shengxiao/miji_compose_ctrl",
	"game/leiji_daily/leiji_daily_ctrl",
	"game/YeWaiGuaJi/yewai_guaji_ctrl",
	"game/group_purchase/group_purchase_ctrl",
	"game/yizhandaodi/yi_zhan_dao_di_ctrl",
	"game/Congratulation/congratulation_ctrl",
	"game/world_question/world_question_ctrl",
	"game/marry_notice/marry_notice_ctrl",
	"game/playpawn/playpawn_ctrl",
	"game/yule/yule_ctrl",
	"game/friend_exp_bottle/friend_exp_bottle_ctrl",
	"game/rolling_barrage/rolling_barrage_ctrl",
	"game/kill_role/kill_role_ctrl",
	"game/treasure_loft/treasure_loft_ctrl",
	"game/serveractivity/treasure_businessman/treasure_businessman_ctrl",
	-- "game/mining/mining_controller",
	"game/screen_shot/screen_shot_ctrl",
	"game/flower_remind/flower_remind_ctrl",
	"game/shenyin/shenyin_ctrl",
	"game/biaobaiqiang/biaobaiqiang_ctrl",

	"game/appearance/appearance_ctrl",
	"game/appearance/multi_mount/multi_mount_ctrl",
	"game/appearance/tou_shi/tou_shi_ctrl",
	"game/appearance/mask/mask_ctrl",
	"game/appearance/waist/waist_ctrl",
	"game/appearance/qilin_bi/qilin_bi_ctrl",
	"game/appearance/upgrade_ctrl",
	"game/bianshen/bian_shen_ctrl",
	"game/kuafu_target/kuafu_target_ctrl",

	"game/increase_capability/increase_capability_ctrl",
	"game/recharge_capacity/recharge_capacity_ctrl",
	"game/consume_discount/consume_discount_ctrl",
	"game/advance/cloak/cloak_ctrl",
	"game/happy_recharge/happy_recharge_ctrl",
	"game/hefuactivity/hefu_activity_ctrl",
	"game/versions_activity/versions_activity_ctrl",
	"game/happy_hit_egg/happy_hit_egg_ctrl",
	"game/clothespress/clothespress_ctrl",
	"game/AdvancedReturn/advanced_return_ctrl",
	"game/AdvancedReturnTwo/advanced_returntwo_ctrl",
	"game/gift_limit_buy/gift_limit_buy_ctrl",
	-- 随机活动专用
	"game/serveractivity/serveractivity_ctrl",
	"game/serveractivity/activite_hongbao/activite_hongbao_ctrl",
	"game/serveractivity/exp_refine/exp_refine_ctrl",
	"game/serveractivity/jinyinta/jinyinta_ctrl",
	"game/serveractivity/collective_goals/collective_goals_ctrl",
	"game/serveractivity/huanzhuang_shop/huanzhuang_shop_ctrl",
	"game/buyone_getone/buyone_getone_ctrl",
	"game/serveractivity/buy_exp/buy_exp_ctrl",
	"game/consume_for_gift/consume_for_gift_ctrl",
	"game/serveractivity/crazy_money_tree/crazy_moneytree_ctrl",
	"game/jubaopen/ju_bao_pen_ctrl",
	"game/fanfanzhuan/fanfanzhuan_ctrl",
	"game/limited_feedback/limited_feedback_ctrl",
	"game/repeat_recharge/repeat_recharge_ctrl",
	"game/lucky_wishing/lucky_wishing_ctrl",
	"game/single_recharge/single_recharge_ctrl",
	"game/serveractivity/zhuanzhuanle/zhuanzhuanle_ctrl",
	"game/serveractivity/expense_gift/expense_gift_ctrl",
	"game/time_limit_sale/time_limit_sale_ctrl",
	"game/kuafu_farmhunting/farmhunting_ctrl",
	"game/rarezhuanlun/rare_zhuanlun_ctrl",
	"game/gold_hunt/gold_hunt_ctrl",
	"game/mapfind/map_find_ctrl",
	"game/image_skill/image_skill_ctrl",
	"game/serveractivity/single_rebate/single_rebate_ctrl",
	"game/lucky_shopping/lucky_shopping_ctrl",
	"game/double_gold/double_gold_ctrl",

	-- "game/planting/planting_ctrl",
	"game/recharge_return_reward/recharge_return_reward_ctrl",
	"game/secretrshop/secretr_shop_ctrl",
	"game/kaifuactivity/activity_login_reward/activity_login_reward_ctrl",
	"game/happy_ernie/happy_ernie_ctrl",
	"game/increase_superior/increase_superior_ctrl",
	"game/longxing/longxing_ctrl",
	"game/lucky_chess/lucky_chess_ctrl",
	"game/timelimitbiggift/time_limit_big_gift_ctrl",
	"game/reset_double_chongzhi/reset_double_chongzhi_ctrl",
	"game/lucky_draw/lucky_draw_ctrl",
	"game/daily_rebate/daily_rebate_ctrl",
	"game/weekend_happy/weekend_happy_ctrl",

	"game/black_market/black_market_ctrl",

	"game/kuafu_liujie_battle/kuafu_liujie_ctrl",

	"game/image_fuling/image_fuling_ctrl",
	"game/kuafu_tuanzhan/kuafu_tuanzhan_ctrl",
	"game/cornucopia/cornucopia_ctrl",
	"game/advance/fabao/fabao_ctrl",
	-- "game/advance/fabao/fabaohuanhua/fabao_huan_hua_ctrl",
	"game/loop_charge_activity/loop_charge_ctrl",
	"game/consume_reward/consume_reward_ctrl",
	"game/one_yuan_snatch/one_yuan_snatch_ctrl",
	"game/kuafu_consumerank/kuafu_consumerank_ctrl",
	"game/small_helper/small_helper_ctrl",
	"game/invest/invest_ctrl",
	"game/helper/helper_ctrl",
	"game/immortal/immortal_ctrl",
	"game/oneyuanbuyview/oneyuanbuy_ctrl",
	"game/wangzhezhijie/wangzhezhijie_ctrl",
	"game/zhizunlingpai/zhizunlingpai_ctrl",
	"game/kf_month_black_wind_high/kf_month_black_wind_high_ctrl",
	"game/luandou_battle/luandou_battle_ctrl",
	"game/fishing/fishing_ctrl",
	"game/littlepet/little_pet_ctrl",
	"game/timelimitgift/time_limit_gift_ctrl",
	"game/ling_kun_battle/ling_kun_battle_ctrl",
	"game/competition_activity/competition_activity_ctrl",
	"game/festivalactivity/festival_activity_ctrl",
	"game/secret_treasure_hunting/secret_treasure_hunting_ctrl",
	"game/festivalactivity/festival_activity_rank/festival_activity_rank_ctrl",
	"game/festivalactivity/festival_single_party/festival_single_party_ctrl",
	"game/festivalactivity/festival_activity_extreme_challenge/extreme_challenge_ctrl",
	"game/festivalactivity/festival_activity_crazy_hi_celebration/crazy_hi_celebration_ctrl",
	"game/festivalactivity/christmagift/christmagift_ctrl",
	"game/shenyu_boss_view/shenyu_boss_ctrl",
	"game/suit_collection/suit_collection_ctrl",
	"game/four_grade_equip/four_grade_equip_ctrl",
	"game/kuafu_borderland_act/kuafu_borderland_ctrl",
	"game/equiment_suit/equiment_suit_ctrl",
	"game/pefect_love/pefect_love_ctrl",
	"game/douqi_equip/douqi_ctrl",
	"game/crazyhappyview/crazy_happy_ctrl",
	"game/jinghuahusong/jinghuahusong_ctrl",
}

return lua_file_list
